// 卷四 · C++ - 模板编程（参考C++ Primer Plus）
const CHAPTER_V4_CPP6 = {
  chapter: "第六章：模板与泛型编程",
  icon: "🧬",
  lessons: [
    {
      id: "v4-cpp6-1",
      title: "函数模板与类模板",
      xp: 35,
      code: '// C++ 模板编程（伪代码展示）\n\n/*\n#include <iostream>\nusing namespace std;\n\n// ========== 函数模板 ==========\ntemplate<typename T>\nT maxValue(T a, T b) {\n    return (a > b) ? a : b;\n}\n\n// ========== 类模板 ==========\ntemplate<typename T, int N>\nclass Array {\nprivate:\n    T data[N];\n    int size = 0;\npublic:\n    void push(T val) {\n        if(size < N) data[size++] = val;\n    }\n    T get(int i) { return data[i]; }\n    int length() { return size; }\n};\n\nint main() {\n    // 函数模板自动推导类型\n    cout << maxValue(3, 7) << endl;      // int\n    cout << maxValue(3.14, 2.71) << endl; // double\n    cout << maxValue(\'a\', \'z\') << endl;   // char\n    \n    // 类模板\n    Array<int, 10> intArr;\n    intArr.push(1);\n    intArr.push(2);\n    intArr.push(3);\n    \n    Array<string, 5> strArr;\n    strArr.push("Hello");\n    strArr.push("World");\n    \n    return 0;\n}\n*/',
      steps: [
        {
          title: "模板：一份代码，多种类型",
          content: '<p><strong>模板</strong>让你编写与类型无关的代码。编译器会根据使用时的类型自动生成对应版本。</p><div class="theory-anim-box"><div class="theory-anim-title">🧬 模板的魔法</div><div style="margin:1rem 0"><div class="t0-fadein" style="animation-delay:0.2s;background:rgba(108,92,231,0.1);border:1px solid rgba(108,92,231,0.3);border-radius:10px;padding:0.8rem;margin-bottom:0.5rem"><div style="font-weight:700;color:#6c5ce7;font-size:0.8rem;margin-bottom:0.3rem">📝 写一次模板</div><div style="font-family:monospace;font-size:0.72rem;color:rgba(255,255,255,0.5);line-height:1.6"><span style="color:#c792ea">template</span>&lt;<span style="color:#c792ea">typename</span> T&gt;<br>T maxValue(T a, T b) { <span style="color:#c792ea">return</span> a > b ? a : b; }</div></div><div style="text-align:center;font-size:1rem;color:rgba(255,255,255,0.2);margin:0.3rem 0">⬇️ 编译器自动展开 ⬇️</div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:0.4rem"><div class="t0-fadein" style="animation-delay:0.4s;background:rgba(0,206,201,0.08);border:1px solid rgba(0,206,201,0.2);border-radius:8px;padding:0.5rem;text-align:center"><div style="font-size:0.65rem;color:#00cec9;font-weight:700">int版本</div><div style="font-size:0.6rem;color:rgba(255,255,255,0.3)">maxValue(3, 7)</div></div><div class="t0-fadein" style="animation-delay:0.6s;background:rgba(255,152,0,0.08);border:1px solid rgba(255,152,0,0.2);border-radius:8px;padding:0.5rem;text-align:center"><div style="font-size:0.65rem;color:#FF9800;font-weight:700">double版本</div><div style="font-size:0.6rem;color:rgba(255,255,255,0.3)">maxValue(3.14, 2.71)</div></div><div class="t0-fadein" style="animation-delay:0.8s;background:rgba(253,121,168,0.08);border:1px solid rgba(253,121,168,0.2);border-radius:8px;padding:0.5rem;text-align:center"><div style="font-size:0.65rem;color:#fd79a8;font-weight:700">string版本</div><div style="font-size:0.6rem;color:rgba(255,255,255,0.3)">maxValue("a","z")</div></div></div></div><div class="theory-callout">💡 STL的所有容器（vector, map, set...）都是类模板！这就是为什么要写<code>vector&lt;int&gt;</code>。</div></div>'
        },
        {
          title: "模板特化与SFINAE",
          content: '<p><strong>模板特化</strong>允许为特定类型提供定制实现，<strong>SFINAE</strong>是C++模板元编程的重要技术。</p><div class="theory-anim-box"><div class="theory-anim-title">🎯 模板特化</div><div style="margin:1rem 0"><div style="background:rgba(0,0,0,0.2);border-radius:8px;padding:0.8rem;font-family:monospace;font-size:0.7rem;line-height:1.8"><span style="color:#546e7a">// 通用模板</span><br><span style="color:#c792ea">template</span>&lt;<span style="color:#c792ea">typename</span> T&gt;<br><span style="color:#c792ea">void</span> <span style="color:#82aaff">print</span>(T val) { cout << val; }<br><br><span style="color:#546e7a">// 特化: 专门处理bool</span><br><span style="color:#c792ea">template</span>&lt;&gt;<br><span style="color:#c792ea">void</span> <span style="color:#82aaff">print</span>&lt;<span style="color:#ffcb6b">bool</span>&gt;(<span style="color:#ffcb6b">bool</span> val) {<br>&nbsp;&nbsp;cout << (val ? <span style="color:#c3e88d">"true"</span> : <span style="color:#c3e88d">"false"</span>);<br>}</div></div><div class="theory-callout">💡 <strong>C++ Primer Plus提醒</strong>：模板编程很强大，但过度使用会导致代码难以理解。应当在<strong>需要类型通用性</strong>时才使用。</div></div>'
        }
      ],
      challenge: {
        desc: "概念题：写出一个模板函数swap(T& a, T& b)的伪代码，交换两个任意类型的变量。",
        hint: "template<typename T>\nvoid mySwap(T& a, T& b) {\n    T temp = a;\n    a = b;\n    b = temp;\n}"
      }
    },
    {
      id: "v4-cpp6-2",
      title: "现代C++特性精选",
      xp: 30,
      code: '// 现代C++特性概览（伪代码）\n\n/*\n#include <iostream>\n#include <tuple>\nusing namespace std;\n\n// ========== auto 自动推导 ==========\nauto x = 42;         // int\nauto pi = 3.14;      // double\nauto name = "Hello"s; // string\n\n// ========== 结构化绑定 (C++17) ==========\nauto [name, age, score] = make_tuple("小王", 10, 95.5);\ncout << name << " " << age << "岁 " << score << "分" << endl;\n\n// ========== constexpr 编译期计算 ==========\nconstexpr int factorial(int n) {\n    return n <= 1 ? 1 : n * factorial(n - 1);\n}\nconstexpr int result = factorial(5); // 编译期计算：120\n\n// ========== 范围for循环 ==========\nvector<int> nums = {1, 2, 3, 4, 5};\nfor (auto& n : nums) {\n    n *= 2; // 直接修改原元素\n}\n\n// ========== optional (C++17) ==========\noptional<string> find(int id) {\n    if (id == 1) return "找到了";\n    return nullopt;\n}\n*/',
      steps: [
        {
          title: "auto, constexpr 与结构化绑定",
          content: '<p>现代C++（11/14/17/20）引入了大量让代码更简洁、更安全的新特性。</p><div class="theory-anim-box"><div class="theory-anim-title">✨ 现代C++特性速览</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:0.6rem;margin:1rem 0"><div class="t0-fadein" style="animation-delay:0.2s;background:rgba(108,92,231,0.1);border:1px solid rgba(108,92,231,0.25);border-radius:10px;padding:0.7rem"><div style="font-weight:800;color:#6c5ce7;font-size:0.8rem;margin-bottom:0.3rem">🔮 auto</div><div style="font-family:monospace;font-size:0.68rem;color:rgba(255,255,255,0.5);line-height:1.8"><span style="color:#c792ea">auto</span> x = <span style="color:#f78c6c">42</span>; <span style="color:#546e7a">// int</span><br><span style="color:#c792ea">auto</span> v = vector{<span style="color:#f78c6c">1,2,3</span>};</div></div><div class="t0-fadein" style="animation-delay:0.3s;background:rgba(0,206,201,0.1);border:1px solid rgba(0,206,201,0.25);border-radius:10px;padding:0.7rem"><div style="font-weight:800;color:#00cec9;font-size:0.8rem;margin-bottom:0.3rem">⚡ constexpr</div><div style="font-family:monospace;font-size:0.68rem;color:rgba(255,255,255,0.5);line-height:1.8"><span style="color:#c792ea">constexpr int</span> fac(<span style="color:#c792ea">int</span> n) {<br>&nbsp;&nbsp;<span style="color:#c792ea">return</span> n<=1?1:n*fac(n-1);<br>} <span style="color:#546e7a">// 编译期算好</span></div></div><div class="t0-fadein" style="animation-delay:0.4s;background:rgba(255,152,0,0.1);border:1px solid rgba(255,152,0,0.25);border-radius:10px;padding:0.7rem"><div style="font-weight:800;color:#FF9800;font-size:0.8rem;margin-bottom:0.3rem">📦 结构化绑定</div><div style="font-family:monospace;font-size:0.68rem;color:rgba(255,255,255,0.5);line-height:1.8"><span style="color:#c792ea">auto</span> [x, y] = pair{<span style="color:#f78c6c">1</span>, <span style="color:#c3e88d">"hi"</span>};<br><span style="color:#546e7a">// x=1, y="hi"</span></div></div><div class="t0-fadein" style="animation-delay:0.5s;background:rgba(253,121,168,0.1);border:1px solid rgba(253,121,168,0.25);border-radius:10px;padding:0.7rem"><div style="font-weight:800;color:#fd79a8;font-size:0.8rem;margin-bottom:0.3rem">🔄 范围for</div><div style="font-family:monospace;font-size:0.68rem;color:rgba(255,255,255,0.5);line-height:1.8"><span style="color:#c792ea">for</span> (<span style="color:#c792ea">auto</span>& item : vec) {<br>&nbsp;&nbsp;cout << item;<br>}</div></div></div></div>'
        },
        {
          title: "C++版本进化时间线",
          content: '<p>C++每3年发布一个新版本，每个版本都带来重要改进。</p><div class="theory-anim-box"><div class="theory-anim-title">📅 C++ 进化之路</div><div style="display:flex;flex-direction:column;gap:0.4rem;margin:1rem 0"><div class="t0-fadein" style="animation-delay:0.2s;display:flex;align-items:center;gap:0.8rem"><div style="width:50px;height:50px;border-radius:50%;background:rgba(108,92,231,0.2);border:2px solid rgba(108,92,231,0.4);display:flex;align-items:center;justify-content:center;font-size:0.7rem;font-weight:900;color:#6c5ce7;flex-shrink:0">C++11</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.5)"><strong style="color:rgba(255,255,255,0.7)">现代C++开端</strong> — auto, lambda, 智能指针, move语义, 范围for</div></div><div class="t0-fadein" style="animation-delay:0.35s;display:flex;align-items:center;gap:0.8rem"><div style="width:50px;height:50px;border-radius:50%;background:rgba(0,206,201,0.2);border:2px solid rgba(0,206,201,0.4);display:flex;align-items:center;justify-content:center;font-size:0.7rem;font-weight:900;color:#00cec9;flex-shrink:0">C++14</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.5)"><strong style="color:rgba(255,255,255,0.7)">完善</strong> — 泛型lambda, make_unique, 二进制字面量</div></div><div class="t0-fadein" style="animation-delay:0.5s;display:flex;align-items:center;gap:0.8rem"><div style="width:50px;height:50px;border-radius:50%;background:rgba(255,152,0,0.2);border:2px solid rgba(255,152,0,0.4);display:flex;align-items:center;justify-content:center;font-size:0.7rem;font-weight:900;color:#FF9800;flex-shrink:0">C++17</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.5)"><strong style="color:rgba(255,255,255,0.7)">实用</strong> — 结构化绑定, optional, string_view, filesystem</div></div><div class="t0-fadein" style="animation-delay:0.65s;display:flex;align-items:center;gap:0.8rem"><div style="width:50px;height:50px;border-radius:50%;background:rgba(253,121,168,0.2);border:2px solid rgba(253,121,168,0.4);display:flex;align-items:center;justify-content:center;font-size:0.7rem;font-weight:900;color:#fd79a8;flex-shrink:0">C++20</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.5)"><strong style="color:rgba(255,255,255,0.7)">革命</strong> — Concepts, Ranges, Coroutines, Modules</div></div></div><div class="theory-callout">💡 学习建议：先掌握<strong>C++11/14</strong>核心特性，再逐步了解17和20的新功能。不要急于追赶最新标准！</div></div>'
        }
      ],
      challenge: {
        desc: "概念题：constexpr和const的区别是什么？constexpr函数有什么限制？",
        hint: "const只保证运行时不被修改，constexpr保证编译期就能计算出结果。constexpr函数必须足够简单，编译器才能在编译期执行。"
      }
    }
  ]
};

registerChapter('cpp', CHAPTER_V4_CPP6);
