// 卷四 · C++ - 指针与内存管理（参考C++ Primer Plus）
const CHAPTER_V4_CPP4 = {
  chapter: "第四章：指针与内存管理",
  icon: "🎯",
  lessons: [
    {
      id: "v4-cpp4-1",
      title: "指针 —— 内存的地址标签",
      xp: 30,
      code: '// 指针基础演示（伪代码展示，非可运行）\n// C++中指针是最强大也最危险的特性之一\n\n/*\n#include <iostream>\nusing namespace std;\n\nint main() {\n    // 变量存储在内存中，有自己的地址\n    int age = 20;\n    cout << "age的值: " << age << endl;\n    cout << "age的地址: " << &age << endl;\n\n    // 指针存储变量的地址\n    int* ptr = &age;\n    cout << "ptr存储的地址: " << ptr << endl;\n    cout << "ptr指向的值: " << *ptr << endl;\n\n    // 通过指针修改原变量\n    *ptr = 25;\n    cout << "修改后age: " << age << endl;\n\n    // 动态内存分配\n    int* arr = new int[5];\n    for(int i = 0; i < 5; i++) {\n        arr[i] = i * 10;\n    }\n    \n    // 释放内存！\n    delete[] arr;\n    return 0;\n}\n*/',
      steps: [
        {
          title: "什么是指针？",
          content: '<p><strong>指针</strong>是存储内存地址的变量。它直接操作内存，是C++最核心的概念之一。</p><div class="theory-anim-box"><div class="theory-anim-title">🎯 指针与变量的关系</div><div style="margin:1rem 0"><div style="display:flex;gap:0.5rem;align-items:center;flex-wrap:wrap;justify-content:center"><div class="t0-fadein" style="animation-delay:0.2s;text-align:center"><div style="font-size:0.65rem;color:rgba(255,255,255,0.4);margin-bottom:0.3rem">变量 age</div><div style="background:rgba(108,92,231,0.2);border:2px solid rgba(108,92,231,0.5);border-radius:8px;padding:0.6rem 1rem"><div style="font-size:1.2rem;font-weight:900;color:#6c5ce7">20</div><div style="font-size:0.55rem;color:rgba(255,255,255,0.3);margin-top:0.2rem">地址: 0x7ffd</div></div></div><div style="font-size:1.5rem;color:rgba(255,255,255,0.2)">←</div><div class="t0-fadein" style="animation-delay:0.5s;text-align:center"><div style="font-size:0.65rem;color:rgba(255,255,255,0.4);margin-bottom:0.3rem">指针 ptr</div><div style="background:rgba(255,152,0,0.2);border:2px solid rgba(255,152,0,0.5);border-radius:8px;padding:0.6rem 1rem"><div style="font-size:0.9rem;font-weight:900;color:#FF9800">0x7ffd</div><div style="font-size:0.55rem;color:rgba(255,255,255,0.3);margin-top:0.2rem">指向age的地址</div></div></div></div><div style="margin-top:1rem;background:rgba(0,0,0,0.2);border-radius:8px;padding:0.6rem;font-family:monospace;font-size:0.72rem;line-height:1.8"><span style="color:#c792ea">int</span> age = <span style="color:#f78c6c">20</span>;<br><span style="color:#c792ea">int</span>* ptr = <span style="color:#89ddff">&</span>age; <span style="color:#546e7a">// & 取地址</span><br>cout << *ptr; <span style="color:#546e7a">// * 解引用 → 输出 20</span></div></div></div>'
        },
        {
          title: "动态内存管理",
          content: '<p>C++允许在运行时动态分配内存，但必须<strong>手动释放</strong>，否则会导致<strong>内存泄漏</strong>。</p><div class="theory-anim-box"><div class="theory-anim-title">💾 new 与 delete</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:0.8rem;margin:1rem 0"><div class="t0-fadein" style="animation-delay:0.2s;background:rgba(105,240,174,0.1);border:2px solid rgba(105,240,174,0.3);border-radius:10px;padding:0.8rem;text-align:center"><div style="font-size:1.5rem;margin-bottom:0.3rem">📦</div><div style="font-weight:800;color:#69F0AE;font-size:0.85rem">new 分配</div><div style="font-family:monospace;font-size:0.7rem;color:rgba(255,255,255,0.5);margin-top:0.3rem;line-height:1.6">int* p = new int(42);<br>int* arr = new int[100];</div></div><div class="t0-fadein" style="animation-delay:0.5s;background:rgba(253,121,168,0.1);border:2px solid rgba(253,121,168,0.3);border-radius:10px;padding:0.8rem;text-align:center"><div style="font-size:1.5rem;margin-bottom:0.3rem">🗑️</div><div style="font-weight:800;color:#fd79a8;font-size:0.85rem">delete 释放</div><div style="font-family:monospace;font-size:0.7rem;color:rgba(255,255,255,0.5);margin-top:0.3rem;line-height:1.6">delete p;<br>delete[] arr;</div></div></div><div class="theory-callout">⚠️ <strong>黄金法则</strong>：每一个new必须对应一个delete！现代C++推荐使用<strong>智能指针</strong>（shared_ptr, unique_ptr）来自动管理内存。</div></div>'
        },
        {
          title: "引用 vs 指针",
          content: '<p><strong>引用</strong>是变量的别名，更安全但功能不如指针灵活。</p><div class="theory-anim-box"><div class="theory-anim-title">⚖️ 引用 vs 指针</div><table style="width:100%;border-collapse:collapse;font-size:0.75rem;margin:0.5rem 0"><tr style="border-bottom:1px solid rgba(255,255,255,0.1)"><th style="padding:0.5rem;text-align:left;color:rgba(255,255,255,0.4)">特性</th><th style="padding:0.5rem;text-align:center;color:#00cec9;font-weight:700">引用 &</th><th style="padding:0.5rem;text-align:center;color:#FF9800;font-weight:700">指针 *</th></tr><tr style="border-bottom:1px solid rgba(255,255,255,0.05)"><td style="padding:0.4rem">可为空</td><td style="padding:0.4rem;text-align:center;color:#69F0AE">❌ 不可</td><td style="padding:0.4rem;text-align:center;color:#fd79a8">✅ 可以</td></tr><tr style="border-bottom:1px solid rgba(255,255,255,0.05)"><td style="padding:0.4rem">可重绑定</td><td style="padding:0.4rem;text-align:center;color:#69F0AE">❌ 不可</td><td style="padding:0.4rem;text-align:center;color:#fd79a8">✅ 可以</td></tr><tr style="border-bottom:1px solid rgba(255,255,255,0.05)"><td style="padding:0.4rem">安全性</td><td style="padding:0.4rem;text-align:center;color:#69F0AE">高</td><td style="padding:0.4rem;text-align:center;color:#fd79a8">低（可能野指针）</td></tr><tr><td style="padding:0.4rem">语法简洁</td><td style="padding:0.4rem;text-align:center;color:#69F0AE">✅ 更简洁</td><td style="padding:0.4rem;text-align:center;color:#fd79a8">需要*和&</td></tr></table><div class="theory-callout">💡 <strong>C++ Primer Plus建议</strong>：能用引用就用引用，需要"可空"或"可重绑定"时才用指针。</div></div>'
        }
      ],
      challenge: {
        desc: "这是概念题：说出以下代码的输出结果（在纸上推演）：int a=10; int* p=&a; *p=20; int& r=a; r=30; 最终a=?",
        hint: "答案：a=30。指针修改a为20，引用再修改a为30。"
      }
    },
    {
      id: "v4-cpp4-2",
      title: "智能指针 —— 自动管理内存的利器",
      xp: 35,
      code: '// 智能指针演示（伪代码展示）\n\n/*\n#include <iostream>\n#include <memory>\nusing namespace std;\n\nclass Dragon {\npublic:\n    string name;\n    Dragon(string n) : name(n) {\n        cout << name << " 诞生!" << endl;\n    }\n    ~Dragon() {\n        cout << name << " 消失!" << endl;\n    }\n    void breatheFire() {\n        cout << name << " 喷出火焰！🔥" << endl;\n    }\n};\n\nint main() {\n    // unique_ptr: 独占所有权\n    {\n        auto dragon1 = make_unique<Dragon>("赤焰龙");\n        dragon1->breatheFire();\n    } // 离开作用域，自动销毁\n    \n    // shared_ptr: 共享所有权\n    {\n        auto dragon2 = make_shared<Dragon>("冰霜龙");\n        cout << "引用计数: " << dragon2.use_count() << endl;\n        {\n            auto dragon2_copy = dragon2;\n            cout << "引用计数: " << dragon2.use_count() << endl;\n        } // dragon2_copy销毁，引用计数-1\n        cout << "引用计数: " << dragon2.use_count() << endl;\n    } // 引用计数归0，自动销毁\n    \n    return 0;\n}\n*/',
      steps: [
        {
          title: "为什么需要智能指针？",
          content: '<p>手动管理内存（new/delete）太容易出错：忘记delete导致<strong>内存泄漏</strong>，或者delete后继续使用导致<strong>悬空指针</strong>。智能指针让C++也能<strong>自动管理内存</strong>！</p><div class="theory-anim-box"><div class="theory-anim-title">🛡️ 三种智能指针</div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:0.6rem;margin:1rem 0"><div class="t0-fadein" style="animation-delay:0.2s;background:rgba(108,92,231,0.12);border:2px solid rgba(108,92,231,0.3);border-radius:12px;padding:0.8rem;text-align:center"><div style="font-size:1.5rem;margin-bottom:0.3rem">👤</div><div style="font-weight:800;color:#6c5ce7;font-size:0.85rem">unique_ptr</div><div style="font-size:0.65rem;color:rgba(255,255,255,0.4);margin-top:0.3rem;line-height:1.5"><strong style="color:rgba(255,255,255,0.6)">独占</strong>所有权<br>不能拷贝<br>只能移动(move)<br>开销最低</div></div><div class="t0-fadein" style="animation-delay:0.4s;background:rgba(0,206,201,0.12);border:2px solid rgba(0,206,201,0.3);border-radius:12px;padding:0.8rem;text-align:center"><div style="font-size:1.5rem;margin-bottom:0.3rem">👥</div><div style="font-weight:800;color:#00cec9;font-size:0.85rem">shared_ptr</div><div style="font-size:0.65rem;color:rgba(255,255,255,0.4);margin-top:0.3rem;line-height:1.5"><strong style="color:rgba(255,255,255,0.6)">共享</strong>所有权<br>引用计数<br>最后一个销毁时释放<br>有少量开销</div></div><div class="t0-fadein" style="animation-delay:0.6s;background:rgba(255,152,0,0.12);border:2px solid rgba(255,152,0,0.3);border-radius:12px;padding:0.8rem;text-align:center"><div style="font-size:1.5rem;margin-bottom:0.3rem">👻</div><div style="font-weight:800;color:#FF9800;font-size:0.85rem">weak_ptr</div><div style="font-size:0.65rem;color:rgba(255,255,255,0.4);margin-top:0.3rem;line-height:1.5"><strong style="color:rgba(255,255,255,0.6)">弱引用</strong><br>不增加引用计数<br>解决循环引用<br>配合shared_ptr</div></div></div></div>'
        },
        {
          title: "shared_ptr 引用计数动画",
          content: '<p><strong>shared_ptr</strong>通过引用计数跟踪有多少指针指向同一对象。计数归零时自动释放内存。</p><div class="theory-anim-box"><div class="theory-anim-title">📊 引用计数可视化</div><div id="rcDemo" style="padding:1rem;text-align:center"><div style="background:rgba(0,206,201,0.12);border:2px solid rgba(0,206,201,0.3);border-radius:12px;padding:0.8rem;display:inline-block;margin-bottom:1rem"><div style="font-size:1.3rem">🐉</div><div style="font-weight:800;color:#00cec9;font-size:0.8rem">Dragon对象</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.5)">引用计数: <span id="rcCount" style="color:#FF9800;font-weight:900;font-size:1rem">0</span></div></div><div style="display:flex;gap:0.5rem;justify-content:center;flex-wrap:wrap;margin:0.5rem 0" id="rcPtrs"></div><div style="display:flex;gap:0.5rem;justify-content:center;margin-top:1rem"><button onclick="rcAdd()" style="padding:0.4rem 1rem;border-radius:8px;border:none;background:linear-gradient(135deg,#00cec9,#81ecec);color:#1a2332;font-weight:700;cursor:pointer;font-size:0.75rem">+ 新增 shared_ptr</button><button onclick="rcRemove()" style="padding:0.4rem 1rem;border-radius:8px;border:none;background:linear-gradient(135deg,#fd79a8,#e84393);color:white;font-weight:700;cursor:pointer;font-size:0.75rem">- 销毁 shared_ptr</button></div><div id="rcLog" style="margin-top:0.8rem;font-family:monospace;font-size:0.68rem;color:rgba(255,255,255,0.5);background:rgba(0,0,0,0.2);border-radius:8px;padding:0.5rem;text-align:left;max-height:80px;overflow-y:auto"></div></div></div><script>var rcN=0;function rcUpdate(){document.getElementById("rcCount").textContent=rcN;var c=document.getElementById("rcPtrs");c.innerHTML="";for(var i=0;i<rcN;i++){c.innerHTML+=\'<div style="background:rgba(108,92,231,0.15);border:1px solid rgba(108,92,231,0.3);border-radius:6px;padding:0.3rem 0.6rem;font-size:0.65rem;color:#6c5ce7;font-weight:700">ptr\'+(i+1)+\'</div>\';}}function rcAdd(){rcN++;rcUpdate();document.getElementById("rcLog").innerHTML+="<div>+ 创建shared_ptr → 引用计数="+rcN+"</div>";}function rcRemove(){if(rcN>0){rcN--;rcUpdate();document.getElementById("rcLog").innerHTML+="<div>- 销毁shared_ptr → 引用计数="+rcN+(rcN===0?" 🗑️ 对象被释放！":"")+"</div>";}}</script>'
        }
      ],
      challenge: {
        desc: "概念题：如果两个shared_ptr互相指向对方（A→B, B→A），会发生什么？用什么解决？",
        hint: "会导致循环引用——引用计数永远不为0，造成内存泄漏。解决方案是将其中一个改为weak_ptr。"
      }
    }
  ]
};

registerChapter('cpp', CHAPTER_V4_CPP4);
