// 卷一 · 理论 - 逻辑入门
const CHAPTER_V1_LOGIC = {
  chapter: "第一章：逻辑入门",
  chapterNum: 1,
  icon: "🧩",
  lessons: [
    {
      id: "v1-logic-1",
      title: "布尔逻辑 —— 真与假的世界",
      xp: 20,
      code: '# 布尔逻辑基础\n\n# True 和 False 是计算机世界的基石\nprint("=== 布尔值 ===")\nprint("True:", True)\nprint("False:", False)\n\n# 逻辑运算\nprint("\\n=== AND 与运算 ===")\nprint("True AND True  =", True and True)\nprint("True AND False =", True and False)\nprint("False AND False =", False and False)\n\nprint("\\n=== OR 或运算 ===")\nprint("True OR False =", True or False)\nprint("False OR False =", False or False)\n\nprint("\\n=== NOT 非运算 ===")\nprint("NOT True  =", not True)\nprint("NOT False =", not False)\n\n# 组合逻辑\nA = True\nB = False\nresult = (A and B) or (not B)\nprint("\\n(True AND False) OR (NOT False) =", result)',
      steps: [
        {
          title: "真与假：计算机的判断基础",
          content: '<p>在计算机的世界里，所有的判断最终都归结为两个值：<strong>真（True）</strong>和<strong>假（False）</strong>。</p><p>这就是<strong>布尔逻辑</strong>，由数学家乔治·布尔在1854年提出，是所有计算机运算的基石。</p><div class="theory-anim-box"><div class="theory-anim-title">🧩 布尔逻辑的三大运算</div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin:1rem 0"><div class="cpu-unit t0-fadein" style="animation-delay:0.2s;text-align:center;padding:1rem;background:rgba(253,121,168,0.15);border:1px solid rgba(253,121,168,0.3);border-radius:12px"><div style="font-size:2rem;margin-bottom:0.5rem">🤝</div><div style="font-weight:800;color:#fd79a8;font-size:1.1rem">AND（与）</div><div style="color:rgba(255,255,255,0.6);font-size:0.75rem;margin-top:0.3rem">两个都为真，结果才为真</div><div style="margin-top:0.5rem;font-family:monospace;font-size:0.7rem;color:rgba(255,255,255,0.5)">1 AND 1 = 1<br>1 AND 0 = 0</div></div><div class="cpu-unit t0-fadein" style="animation-delay:0.5s;text-align:center;padding:1rem;background:rgba(0,206,201,0.15);border:1px solid rgba(0,206,201,0.3);border-radius:12px"><div style="font-size:2rem;margin-bottom:0.5rem">✋</div><div style="font-weight:800;color:#00cec9;font-size:1.1rem">OR（或）</div><div style="color:rgba(255,255,255,0.6);font-size:0.75rem;margin-top:0.3rem">只要有一个为真，结果就为真</div><div style="margin-top:0.5rem;font-family:monospace;font-size:0.7rem;color:rgba(255,255,255,0.5)">0 OR 1 = 1<br>0 OR 0 = 0</div></div><div class="cpu-unit t0-fadein" style="animation-delay:0.8s;text-align:center;padding:1rem;background:rgba(253,121,168,0.15);border:1px solid rgba(253,121,168,0.3);border-radius:12px"><div style="font-size:2rem;margin-bottom:0.5rem">🔄</div><div style="font-weight:800;color:#fd79a8;font-size:1.1rem">NOT（非）</div><div style="color:rgba(255,255,255,0.6);font-size:0.75rem;margin-top:0.3rem">取反：真变假，假变真</div><div style="margin-top:0.5rem;font-family:monospace;font-size:0.7rem;color:rgba(255,255,255,0.5)">NOT 1 = 0<br>NOT 0 = 1</div></div></div><div class="theory-callout">💡 你电脑里的CPU每秒执行数十亿次这样的逻辑运算！</div></div>'
        },
        {
          title: "逻辑门 —— 硬件中的布尔运算",
          content: '<p>在真实的计算机芯片中，布尔运算通过<strong>逻辑门</strong>实现，它们是由晶体管组成的微型电路。</p><div class="theory-anim-box"><div class="theory-anim-title">⚡ 交互式逻辑门模拟器</div><div id="logicGateSim" style="text-align:center;padding:1rem"><div style="display:flex;align-items:center;justify-content:center;gap:2rem;flex-wrap:wrap"><div><div style="font-size:0.75rem;color:rgba(255,255,255,0.5);margin-bottom:0.5rem">输入 A</div><button onclick="this.dataset.v=this.dataset.v===\'1\'?\'0\':\'1\';this.textContent=this.dataset.v===\'1\'?\'1 (真)\':\'0 (假)\';this.style.background=this.dataset.v===\'1\'?\'rgba(0,206,201,0.3)\':\'rgba(255,255,255,0.1)\';updateLogicGate()" data-v="0" style="padding:0.8rem 1.5rem;border-radius:10px;border:2px solid rgba(255,255,255,0.2);background:rgba(255,255,255,0.1);color:white;font-size:1rem;font-weight:800;cursor:pointer;transition:all 0.3s" id="lgInputA">0 (假)</button></div><div><div style="font-size:0.75rem;color:rgba(255,255,255,0.5);margin-bottom:0.5rem">运算</div><select onchange="updateLogicGate()" id="lgOp" style="padding:0.8rem 1rem;border-radius:10px;border:2px solid rgba(253,121,168,0.4);background:rgba(253,121,168,0.2);color:white;font-size:0.9rem;font-weight:700;cursor:pointer"><option value="AND">AND</option><option value="OR">OR</option><option value="XOR">XOR</option><option value="NAND">NAND</option></select></div><div><div style="font-size:0.75rem;color:rgba(255,255,255,0.5);margin-bottom:0.5rem">输入 B</div><button onclick="this.dataset.v=this.dataset.v===\'1\'?\'0\':\'1\';this.textContent=this.dataset.v===\'1\'?\'1 (真)\':\'0 (假)\';this.style.background=this.dataset.v===\'1\'?\'rgba(0,206,201,0.3)\':\'rgba(255,255,255,0.1)\';updateLogicGate()" data-v="0" style="padding:0.8rem 1.5rem;border-radius:10px;border:2px solid rgba(255,255,255,0.2);background:rgba(255,255,255,0.1);color:white;font-size:1rem;font-weight:800;cursor:pointer;transition:all 0.3s" id="lgInputB">0 (假)</button></div><div style="font-size:2rem;color:rgba(255,255,255,0.3)">=</div><div><div style="font-size:0.75rem;color:rgba(255,255,255,0.5);margin-bottom:0.5rem">结果</div><div id="lgResult" style="padding:0.8rem 1.5rem;border-radius:10px;border:2px solid rgba(255,152,0,0.4);background:rgba(255,152,0,0.15);font-size:1rem;font-weight:800;color:#FF9800;min-width:80px">0 (假)</div></div></div></div></div><script>function updateLogicGate(){var a=document.getElementById("lgInputA").dataset.v==="1",b=document.getElementById("lgInputB").dataset.v==="1",op=document.getElementById("lgOp").value,r=false;if(op==="AND")r=a&&b;else if(op==="OR")r=a||b;else if(op==="XOR")r=a!==b;else if(op==="NAND")r=!(a&&b);var el=document.getElementById("lgResult");el.textContent=r?"1 (真)":"0 (假)";el.style.borderColor=r?"rgba(0,206,201,0.6)":"rgba(255,152,0,0.4)";el.style.background=r?"rgba(0,206,201,0.2)":"rgba(255,152,0,0.15)";el.style.color=r?"#00cec9":"#FF9800";}</script>'
        },
        {
          title: "真值表 —— 逻辑运算的完整地图",
          content: '<p>每个逻辑运算都有一个<strong>真值表</strong>，它列出了所有可能的输入组合和对应的输出结果。</p><div class="theory-anim-box"><div class="theory-anim-title">📊 真值表动画演示</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:1rem 0"><div style="background:rgba(253,121,168,0.1);border-radius:10px;padding:0.8rem"><div style="font-weight:700;color:#fd79a8;margin-bottom:0.5rem;text-align:center">AND 真值表</div><table style="width:100%;border-collapse:collapse;font-size:0.75rem;font-family:monospace"><tr style="color:rgba(255,255,255,0.5)"><th style="padding:4px">A</th><th style="padding:4px">B</th><th style="padding:4px">A AND B</th></tr><tr class="t0-fadein" style="animation-delay:0.2s"><td style="padding:4px;text-align:center">0</td><td style="padding:4px;text-align:center">0</td><td style="padding:4px;text-align:center;color:#fd79a8">0</td></tr><tr class="t0-fadein" style="animation-delay:0.4s"><td style="padding:4px;text-align:center">0</td><td style="padding:4px;text-align:center">1</td><td style="padding:4px;text-align:center;color:#fd79a8">0</td></tr><tr class="t0-fadein" style="animation-delay:0.6s"><td style="padding:4px;text-align:center">1</td><td style="padding:4px;text-align:center">0</td><td style="padding:4px;text-align:center;color:#fd79a8">0</td></tr><tr class="t0-fadein" style="animation-delay:0.8s"><td style="padding:4px;text-align:center">1</td><td style="padding:4px;text-align:center">1</td><td style="padding:4px;text-align:center;color:#00cec9;font-weight:700">1</td></tr></table></div><div style="background:rgba(0,206,201,0.1);border-radius:10px;padding:0.8rem"><div style="font-weight:700;color:#00cec9;margin-bottom:0.5rem;text-align:center">OR 真值表</div><table style="width:100%;border-collapse:collapse;font-size:0.75rem;font-family:monospace"><tr style="color:rgba(255,255,255,0.5)"><th style="padding:4px">A</th><th style="padding:4px">B</th><th style="padding:4px">A OR B</th></tr><tr class="t0-fadein" style="animation-delay:0.3s"><td style="padding:4px;text-align:center">0</td><td style="padding:4px;text-align:center">0</td><td style="padding:4px;text-align:center;color:#fd79a8">0</td></tr><tr class="t0-fadein" style="animation-delay:0.5s"><td style="padding:4px;text-align:center">0</td><td style="padding:4px;text-align:center">1</td><td style="padding:4px;text-align:center;color:#00cec9;font-weight:700">1</td></tr><tr class="t0-fadein" style="animation-delay:0.7s"><td style="padding:4px;text-align:center">1</td><td style="padding:4px;text-align:center">0</td><td style="padding:4px;text-align:center;color:#00cec9;font-weight:700">1</td></tr><tr class="t0-fadein" style="animation-delay:0.9s"><td style="padding:4px;text-align:center">1</td><td style="padding:4px;text-align:center">1</td><td style="padding:4px;text-align:center;color:#00cec9;font-weight:700">1</td></tr></table></div></div><div class="theory-callout">🎯 记住：AND像"挑剔的门卫"——两个都要对才放行；OR像"宽容的门卫"——有一个对就放行</div></div>'
        }
      ],
      challenge: {
        description: "写一个程序判断：变量 age=20, has_ticket=True，判断 age >= 18 AND has_ticket 是否为 True，打印结果。",
        hint: "使用 and 运算符组合两个条件",
        solution: 'age = 20\nhas_ticket = True\nresult = age >= 18 and has_ticket\nprint(result)'
      }
    },
    {
      id: "v1-logic-2",
      title: "命题逻辑 —— 推理的科学",
      xp: 25,
      code: '# 命题逻辑与推理\n\nprint("=== 命题逻辑 ===")\nprint("命题：可以判断真假的陈述句")\nprint()\n\n# 命题示例\np = True   # 命题P：今天是周一\nq = False  # 命题Q：正在下雨\n\nprint("P (今天是周一):", p)\nprint("Q (正在下雨):", q)\n\n# 蕴含关系：如果P，则Q\n# P -> Q 等价于 (not P) or Q\nimplication = (not p) or q\nprint(f"\\nP → Q (如果周一则下雨): {implication}")\n\n# 逆命题、否命题、逆否命题\nprint("\\n=== 四种命题关系 ===")\nprint(f"原命题  P → Q  : {(not p) or q}")\nprint(f"逆命题  Q → P  : {(not q) or p}")\nprint(f"否命题  ¬P → ¬Q: {p or (not q)}")\nprint(f"逆否命题 ¬Q → ¬P: {q or (not p)}")\n\nprint("\\n💡 原命题和逆否命题永远等价！")\n\n# 德摩根定律\nA = True\nB = False\nprint(f"\\n=== 德摩根定律 ===")\nprint(f"NOT(A AND B) = {not(A and B)}")\nprint(f"(NOT A) OR (NOT B) = {(not A) or (not B)}")\nprint(f"两者相等: {not(A and B) == ((not A) or (not B))}")',
      steps: [
        {
          title: "什么是命题？",
          content: '<p><strong>命题</strong>是一个可以判断真假的陈述句。它是逻辑推理的基本单元。</p><div class="theory-anim-box"><div class="theory-anim-title">📝 命题的判断</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:0.8rem;margin:1rem 0"><div style="background:rgba(0,206,201,0.1);border:1px solid rgba(0,206,201,0.3);border-radius:10px;padding:0.8rem"><div style="font-weight:700;color:#00cec9;margin-bottom:0.5rem;font-size:0.85rem">✅ 是命题</div><div style="font-size:0.75rem;color:rgba(255,255,255,0.6);line-height:1.8">• "2 + 3 = 5"（真）<br>• "地球是平的"（假）<br>• "Python是编程语言"（真）<br>• "100 > 200"（假）</div></div><div style="background:rgba(253,121,168,0.1);border:1px solid rgba(253,121,168,0.3);border-radius:10px;padding:0.8rem"><div style="font-weight:700;color:#fd79a8;margin-bottom:0.5rem;font-size:0.85rem">❌ 不是命题</div><div style="font-size:0.75rem;color:rgba(255,255,255,0.6);line-height:1.8">• "今天天气好吗？"（疑问句）<br>• "请打开窗户"（祈使句）<br>• "x > 5"（含变量，不确定）<br>• "好美啊！"（感叹句）</div></div></div></div>'
        },
        {
          title: "蕴含与逆否命题",
          content: '<p><strong>蕴含（→）</strong>是逻辑中最重要的连接词："如果P，则Q"。</p><div class="theory-anim-box"><div class="theory-anim-title">🔗 四种命题关系</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:0.6rem;margin:1rem 0"><div class="t0-fadein" style="animation-delay:0.2s;background:rgba(253,121,168,0.12);border:1px solid rgba(253,121,168,0.3);border-radius:10px;padding:0.8rem;text-align:center"><div style="font-weight:800;color:#fd79a8;font-size:0.9rem">原命题</div><div style="font-size:0.75rem;color:rgba(255,255,255,0.5);margin-top:0.3rem">如果下雨，则地面湿</div><div style="font-family:monospace;font-size:0.7rem;color:rgba(255,255,255,0.4);margin-top:0.2rem">P → Q</div></div><div class="t0-fadein" style="animation-delay:0.4s;background:rgba(0,206,201,0.12);border:1px solid rgba(0,206,201,0.3);border-radius:10px;padding:0.8rem;text-align:center"><div style="font-weight:800;color:#00cec9;font-size:0.9rem">逆命题</div><div style="font-size:0.75rem;color:rgba(255,255,255,0.5);margin-top:0.3rem">如果地面湿，则下雨</div><div style="font-family:monospace;font-size:0.7rem;color:rgba(255,255,255,0.4);margin-top:0.2rem">Q → P（不一定成立！）</div></div><div class="t0-fadein" style="animation-delay:0.6s;background:rgba(255,152,0,0.12);border:1px solid rgba(255,152,0,0.3);border-radius:10px;padding:0.8rem;text-align:center"><div style="font-weight:800;color:#FF9800;font-size:0.9rem">否命题</div><div style="font-size:0.75rem;color:rgba(255,255,255,0.5);margin-top:0.3rem">如果不下雨，则地面不湿</div><div style="font-family:monospace;font-size:0.7rem;color:rgba(255,255,255,0.4);margin-top:0.2rem">¬P → ¬Q（不一定成立！）</div></div><div class="t0-fadein" style="animation-delay:0.8s;background:rgba(105,240,174,0.12);border:1px solid rgba(105,240,174,0.3);border-radius:10px;padding:0.8rem;text-align:center"><div style="font-weight:800;color:#69F0AE;font-size:0.9rem">逆否命题 ✓</div><div style="font-size:0.75rem;color:rgba(255,255,255,0.5);margin-top:0.3rem">如果地面不湿，则没下雨</div><div style="font-family:monospace;font-size:0.7rem;color:rgba(255,255,255,0.4);margin-top:0.2rem">¬Q → ¬P（一定成立！）</div></div></div><div class="theory-callout">🎯 <strong>关键定理</strong>：原命题与逆否命题永远等价！这在数学证明中非常重要。</div></div>'
        },
        {
          title: "德摩根定律",
          content: '<p><strong>德摩根定律</strong>是逻辑学中最优美的定理之一，它揭示了AND和OR之间的深层联系。</p><div class="theory-anim-box"><div class="theory-anim-title">⚡ 德摩根定律</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:1rem 0"><div class="t0-fadein" style="animation-delay:0.3s;background:linear-gradient(135deg,rgba(253,121,168,0.12),rgba(253,121,168,0.08));border:1px solid rgba(253,121,168,0.3);border-radius:12px;padding:1rem;text-align:center"><div style="font-size:1.5rem;margin-bottom:0.3rem">📐</div><div style="font-weight:800;color:#fd79a8;font-size:0.9rem">定律一</div><div style="font-family:monospace;font-size:0.85rem;color:rgba(255,255,255,0.7);margin:0.5rem 0;background:rgba(0,0,0,0.2);padding:0.4rem;border-radius:6px">NOT(A AND B) =<br>(NOT A) OR (NOT B)</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.4)">不是（两个都对）= 至少一个不对</div></div><div class="t0-fadein" style="animation-delay:0.6s;background:linear-gradient(135deg,rgba(0,206,201,0.12),rgba(255,152,0,0.08));border:1px solid rgba(0,206,201,0.3);border-radius:12px;padding:1rem;text-align:center"><div style="font-size:1.5rem;margin-bottom:0.3rem">📐</div><div style="font-weight:800;color:#00cec9;font-size:0.9rem">定律二</div><div style="font-family:monospace;font-size:0.85rem;color:rgba(255,255,255,0.7);margin:0.5rem 0;background:rgba(0,0,0,0.2);padding:0.4rem;border-radius:6px">NOT(A OR B) =<br>(NOT A) AND (NOT B)</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.4)">不是（至少一个对）= 两个都不对</div></div></div><div class="theory-callout">💡 德摩根定律在编程中超级有用！比如<code>if not (a and b)</code>等价于<code>if (not a) or (not b)</code></div></div>'
        }
      ],
      challenge: {
        desc: "验证德摩根定律：对所有 A, B 的组合(True/False)，验证 not(A and B) == (not A) or (not B)。",
        template: '# 验证德摩根定律\nfor A in [True, False]:\n    for B in [True, False]:\n        left = # 你的代码\n        right = # 你的代码\n        print(f"A={A}, B={B}: {left} == {right} -> {left == right}")',
        check: function(output) { return output.indexOf('True') !== -1 && output.split('True').length >= 5; },
        hint: '# 验证德摩根定律\nfor A in [True, False]:\n    for B in [True, False]:\n        left = not(A and B)\n        right = (not A) or (not B)\n        print(f"A={A}, B={B}: {left} == {right} -> {left == right}")'
      }
    },
    {
      id: "v1-logic-3",
      title: "集合论基础 —— 分类的艺术",
      xp: 25,
      code: '# 集合论基础\n\nprint("=== 集合 ===")\nA = {1, 2, 3, 4, 5}\nB = {4, 5, 6, 7, 8}\nprint("集合A:", A)\nprint("集合B:", B)\n\nprint("\\n=== 集合运算 ===")\nprint("并集 A ∪ B:", A | B)\nprint("交集 A ∩ B:", A & B)\nprint("差集 A - B:", A - B)\nprint("对称差 A △ B:", A ^ B)\n\nprint("\\n=== 子集关系 ===")\nC = {1, 2, 3}\nprint(f"C = {C}")\nprint(f"C ⊆ A? {C <= A}")\nprint(f"C ⊆ B? {C <= B}")\n\n# 笛卡尔积\nprint("\\n=== 笛卡尔积 ===")\nX = {"红", "蓝"}\nY = {"大", "小"}\nproduct = [(x, y) for x in X for y in Y]\nprint(f"X × Y = {product}")\nprint(f"|X × Y| = {len(product)} = {len(X)} × {len(Y)}")',
      steps: [
        {
          title: "集合：万物皆可分类",
          content: '<p><strong>集合</strong>是一组不重复元素的无序集合。它是数学和计算机科学的基础概念。</p><div class="theory-anim-box"><div class="theory-anim-title">🎯 集合运算可视化</div><div style="display:flex;justify-content:center;align-items:center;margin:1rem 0;padding:1rem"><div style="position:relative;width:280px;height:180px"><div class="t0-fadein" style="animation-delay:0.2s;position:absolute;left:0;top:10px;width:180px;height:160px;border-radius:50%;border:3px solid rgba(253,121,168,0.6);background:rgba(253,121,168,0.08)"><div style="position:absolute;left:25px;top:60px;font-size:0.7rem;color:#fd79a8;font-weight:700">1, 2, 3</div></div><div class="t0-fadein" style="animation-delay:0.4s;position:absolute;right:0;top:10px;width:180px;height:160px;border-radius:50%;border:3px solid rgba(0,206,201,0.6);background:rgba(0,206,201,0.08)"><div style="position:absolute;right:25px;top:60px;font-size:0.7rem;color:#00cec9;font-weight:700">6, 7, 8</div></div><div class="t0-fadein" style="animation-delay:0.6s;position:absolute;left:100px;top:55px;font-size:0.8rem;color:#FF9800;font-weight:800;z-index:1">4, 5</div><div style="position:absolute;left:10px;top:0;font-size:0.75rem;color:#fd79a8;font-weight:700">A</div><div style="position:absolute;right:10px;top:0;font-size:0.75rem;color:#00cec9;font-weight:700">B</div></div></div><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:0.6rem;margin-top:0.5rem;font-size:0.75rem"><div style="background:rgba(253,121,168,0.1);border-radius:8px;padding:0.5rem;text-align:center"><span style="color:#fd79a8;font-weight:700">A ∪ B</span> = {1,2,3,4,5,6,7,8}</div><div style="background:rgba(255,152,0,0.1);border-radius:8px;padding:0.5rem;text-align:center"><span style="color:#FF9800;font-weight:700">A ∩ B</span> = {4, 5}</div><div style="background:rgba(253,121,168,0.1);border-radius:8px;padding:0.5rem;text-align:center"><span style="color:#fd79a8;font-weight:700">A - B</span> = {1, 2, 3}</div><div style="background:rgba(0,206,201,0.1);border-radius:8px;padding:0.5rem;text-align:center"><span style="color:#00cec9;font-weight:700">B - A</span> = {6, 7, 8}</div></div></div>'
        },
        {
          title: "子集与幂集",
          content: '<p><strong>子集</strong>是包含于另一个集合中的集合。<strong>幂集</strong>是一个集合所有子集的集合。</p><div class="theory-anim-box"><div class="theory-anim-title">📊 幂集的指数爆炸</div><div style="margin:1rem 0"><div style="display:grid;grid-template-columns:auto 1fr;gap:0.5rem 1rem;font-size:0.75rem;align-items:center"><div class="t0-fadein" style="animation-delay:0.2s;font-weight:700;color:#fd79a8">{a}</div><div class="t0-fadein" style="animation-delay:0.2s;color:rgba(255,255,255,0.5)">幂集: {∅, {a}} → 2¹ = <span style="color:#FF9800;font-weight:700">2</span> 个子集</div><div class="t0-fadein" style="animation-delay:0.4s;font-weight:700;color:#00cec9">{a, b}</div><div class="t0-fadein" style="animation-delay:0.4s;color:rgba(255,255,255,0.5)">幂集: {∅, {a}, {b}, {a,b}} → 2² = <span style="color:#FF9800;font-weight:700">4</span> 个子集</div><div class="t0-fadein" style="animation-delay:0.6s;font-weight:700;color:#fd79a8">{a, b, c}</div><div class="t0-fadein" style="animation-delay:0.6s;color:rgba(255,255,255,0.5)">幂集: 2³ = <span style="color:#FF9800;font-weight:700">8</span> 个子集</div><div class="t0-fadein" style="animation-delay:0.8s;font-weight:700;color:#FF9800">{a, b, c, d}</div><div class="t0-fadein" style="animation-delay:0.8s;color:rgba(255,255,255,0.5)">幂集: 2⁴ = <span style="color:#FF9800;font-weight:700">16</span> 个子集</div></div></div><div class="theory-callout">💡 n个元素的集合有 2ⁿ 个子集。这就是为什么集合问题常常导致<strong>指数级复杂度</strong>！</div></div>'
        }
      ],
      challenge: {
        desc: "计算集合 {1,2,3} 的所有子集，打印出来。",
        template: '# 求 {1,2,3} 的所有子集\nfrom itertools import combinations\nS = {1, 2, 3}\n# 你的代码',
        check: function(output) { return output.indexOf('()') !== -1 || output.indexOf('set()') !== -1 || output.indexOf('[]') !== -1; },
        hint: 'S = [1, 2, 3]\nresult = []\nfor i in range(len(S) + 1):\n    for combo in combinations(S, i):\n        result.append(set(combo))\nfor s in result:\n    print(s)'
      }
    },
    {
      id: "v1-logic-4",
      title: "逻辑推理 —— 像侦探一样思考",
      xp: 30,
      code: '# 逻辑推理实战\n\nprint("=== 逻辑推理三段论 ===")\nprint("前提1: 所有程序员都会写代码")\nprint("前提2: 小明是程序员")\nprint("结论: 小明会写代码 ✓")\n\n# 用Python模拟推理\ndef syllogism(premise1, premise2):\n    """三段论推理器"""\n    # premise1: (类别, 属性) - "所有X都是Y"\n    # premise2: (个体, 类别) - "Z是X"\n    category, attribute = premise1\n    individual, ind_category = premise2\n    if ind_category == category:\n        return f"{individual}是{attribute}"\n    return "无法推出结论"\n\nresult = syllogism(("程序员", "会写代码"), ("小明", "程序员"))\nprint(f"推理结果: {result}")\n\nprint("\\n=== 反证法 ===")\nprint("命题: √2 是无理数")\nprint("假设 √2 = p/q (p,q互质)")\nprint("则 2 = p²/q², 即 p² = 2q²")\nprint("→ p是偶数, 设p=2k")\nprint("→ 4k² = 2q², 即 q²=2k²")\nprint("→ q也是偶数")\nprint("→ p,q都是偶数，与互质矛盾！")\nprint("∴ √2 是无理数 ✓")\n\n# 逻辑谜题\nprint("\\n=== 逻辑谜题 ===")\nprint("A说:B说谎  B说:C说谎  C说:A和B都说谎")\n# 暴力求解\nfor a_truth in [True, False]:\n    for b_truth in [True, False]:\n        for c_truth in [True, False]:\n            a_says = (b_truth == False)\n            b_says = (c_truth == False)\n            c_says = (a_truth == False and b_truth == False)\n            if (a_truth == a_says) and (b_truth == b_says) and (c_truth == c_says):\n                print(f"A:{"诚实" if a_truth else "说谎"} B:{"诚实" if b_truth else "说谎"} C:{"诚实" if c_truth else "说谎"}")',
      steps: [
        {
          title: "三段论 —— 逻辑推理的基石",
          content: '<p><strong>三段论</strong>是亚里士多德提出的经典推理模式，由两个前提推出一个结论。</p><div class="theory-anim-box"><div class="theory-anim-title">🏛️ 三段论推理</div><div style="max-width:400px;margin:1rem auto"><div class="t0-fadein" style="animation-delay:0.2s;background:rgba(253,121,168,0.12);border:1px solid rgba(253,121,168,0.3);border-radius:10px;padding:0.7rem;margin-bottom:0.5rem;display:flex;align-items:center;gap:0.5rem"><div style="background:#fd79a8;color:white;width:26px;height:26px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:0.7rem;font-weight:800;flex-shrink:0">1</div><div style="font-size:0.8rem;color:rgba(255,255,255,0.7)"><strong style="color:#fd79a8">大前提：</strong>所有鱼都生活在水里</div></div><div class="t0-fadein" style="animation-delay:0.5s;background:rgba(0,206,201,0.12);border:1px solid rgba(0,206,201,0.3);border-radius:10px;padding:0.7rem;margin-bottom:0.5rem;display:flex;align-items:center;gap:0.5rem"><div style="background:#00cec9;color:white;width:26px;height:26px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:0.7rem;font-weight:800;flex-shrink:0">2</div><div style="font-size:0.8rem;color:rgba(255,255,255,0.7)"><strong style="color:#00cec9">小前提：</strong>金鱼是鱼</div></div><div style="text-align:center;font-size:1.5rem;margin:0.3rem 0;color:rgba(255,255,255,0.2)">⬇️</div><div class="t0-fadein" style="animation-delay:0.8s;background:rgba(105,240,174,0.12);border:2px solid rgba(105,240,174,0.4);border-radius:10px;padding:0.7rem;display:flex;align-items:center;gap:0.5rem"><div style="background:#69F0AE;color:#1a2332;width:26px;height:26px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:0.7rem;font-weight:800;flex-shrink:0">✓</div><div style="font-size:0.8rem;color:rgba(255,255,255,0.7)"><strong style="color:#69F0AE">结论：</strong>金鱼生活在水里</div></div></div></div>'
        },
        {
          title: "常见逻辑谬误",
          content: '<p>学会逻辑推理，也要学会识别<strong>逻辑谬误</strong>——看起来正确但实际有错的推理。</p><div class="theory-anim-box"><div class="theory-anim-title">⚠️ 常见逻辑谬误</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:0.8rem;margin:1rem 0"><div class="t0-fadein" style="animation-delay:0.2s;background:rgba(253,121,168,0.1);border:1px solid rgba(253,121,168,0.3);border-radius:10px;padding:0.8rem"><div style="font-weight:800;color:#fd79a8;font-size:0.85rem;margin-bottom:0.3rem">🔄 肯定后件</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.5);line-height:1.6">如果下雨，地面湿<br>地面湿了<br><span style="color:#fd79a8">∴ 下雨了 ❌</span><br><span style="font-size:0.65rem;color:rgba(255,255,255,0.3)">（也可能是洒水车）</span></div></div><div class="t0-fadein" style="animation-delay:0.4s;background:rgba(255,152,0,0.1);border:1px solid rgba(255,152,0,0.3);border-radius:10px;padding:0.8rem"><div style="font-weight:800;color:#FF9800;font-size:0.85rem;margin-bottom:0.3rem">🎭 稻草人谬误</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.5);line-height:1.6">A说：我们应该减少糖摄入<br>B说：A要我们什么甜的都不吃！<br><span style="color:#FF9800">扭曲了A的观点 ❌</span></div></div><div class="t0-fadein" style="animation-delay:0.6s;background:rgba(253,121,168,0.1);border:1px solid rgba(253,121,168,0.3);border-radius:10px;padding:0.8rem"><div style="font-weight:800;color:#fd79a8;font-size:0.85rem;margin-bottom:0.3rem">🔢 相关≠因果</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.5);line-height:1.6">冰淇淋销量↑，溺水事件↑<br><span style="color:#fd79a8">∴ 冰淇淋导致溺水？ ❌</span><br><span style="font-size:0.65rem;color:rgba(255,255,255,0.3)">（都是夏天导致的）</span></div></div><div class="t0-fadein" style="animation-delay:0.8s;background:rgba(0,206,201,0.1);border:1px solid rgba(0,206,201,0.3);border-radius:10px;padding:0.8rem"><div style="font-weight:800;color:#00cec9;font-size:0.85rem;margin-bottom:0.3rem">⛰️ 滑坡谬误</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.5);line-height:1.6">如果允许迟到1分钟<br>→ 就会迟到10分钟<br>→ 就不来上课了<br><span style="color:#00cec9">过度推导 ❌</span></div></div></div></div>'
        },
        {
          title: "用程序求解逻辑谜题",
          content: '<p>逻辑谜题可以用<strong>穷举法</strong>解决——让计算机遍历所有可能的情况！</p><div class="theory-anim-box"><div class="theory-anim-title">🧩 经典逻辑谜题</div><div style="background:rgba(255,152,0,0.08);border:1px solid rgba(255,152,0,0.2);border-radius:10px;padding:1rem;margin:0.5rem 0"><div style="font-weight:800;color:#FF9800;margin-bottom:0.5rem;font-size:0.85rem">🏝️ 诚实岛与说谎岛</div><div style="font-size:0.78rem;color:rgba(255,255,255,0.6);line-height:1.7">岛上有两种人：诚实者（永远说真话）和说谎者（永远说假话）。<br>• A说："B是说谎者"<br>• B说："C是说谎者"<br>• C说："A和B都是说谎者"<br><br><strong style="color:rgba(255,255,255,0.8)">解题思路：</strong>遍历所有 2³ = 8 种可能！</div></div><div style="background:rgba(0,0,0,0.2);border-radius:8px;padding:0.6rem;font-family:monospace;font-size:0.7rem;color:rgba(255,255,255,0.5);margin-top:0.5rem;line-height:1.8"><span style="color:#c792ea">for</span> a <span style="color:#89ddff">in</span> [True, False]:<br>&nbsp;&nbsp;<span style="color:#c792ea">for</span> b <span style="color:#89ddff">in</span> [True, False]:<br>&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#c792ea">for</span> c <span style="color:#89ddff">in</span> [True, False]:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="color:#546e7a"># 检查每个人的话是否与自身身份一致</span></div></div>'
        }
      ],
      challenge: {
        desc: "用穷举法解这个谜题：A说B说谎，B说C说谎，C说A和B都说谎。谁诚实谁说谎？",
        template: '# 逻辑谜题求解\nfor a in [True, False]:\n    for b in [True, False]:\n        for c in [True, False]:\n            # 你的代码\n            pass',
        check: function(output) { return output.indexOf('诚实') !== -1 || output.indexOf('说谎') !== -1 || output.indexOf('True') !== -1; },
        hint: 'for a in [True, False]:\n    for b in [True, False]:\n        for c in [True, False]:\n            a_says = (b == False)\n            b_says = (c == False)\n            c_says = (a == False and b == False)\n            if (a == a_says) and (b == b_says) and (c == c_says):\n                print(f"A:{\"诚实\" if a else \"说谎\"} B:{\"诚实\" if b else \"说谎\"} C:{\"诚实\" if c else \"说谎\"}")'
      }
    }
  ]
};

registerChapter('theory', CHAPTER_V1_LOGIC);
