// 卷四 · C++ - 异常处理与文件I/O（参考C++ Primer Plus）
const CHAPTER_V4_CPP7 = {
  chapter: "第七章：异常处理与文件I/O",
  icon: "🛡️",
  lessons: [
    {
      id: "v4-cpp7-1",
      title: "异常处理 —— 优雅地应对错误",
      xp: 25,
      code: '// C++ 异常处理（伪代码展示）\n\n/*\n#include <iostream>\n#include <stdexcept>\n#include <fstream>\nusing namespace std;\n\n// ========== 异常处理 ==========\ndouble divide(double a, double b) {\n    if (b == 0) {\n        throw runtime_error("除数不能为零！");\n    }\n    return a / b;\n}\n\nint main() {\n    // try-catch 捕获异常\n    try {\n        cout << divide(10, 3) << endl;   // 正常\n        cout << divide(10, 0) << endl;   // 抛出异常\n    } catch (const runtime_error& e) {\n        cerr << "错误: " << e.what() << endl;\n    } catch (...) {\n        cerr << "未知错误！" << endl;\n    }\n    \n    // ========== 文件读写 ==========\n    // 写文件\n    ofstream outFile("test.txt");\n    if (outFile.is_open()) {\n        outFile << "Hello, C++!" << endl;\n        outFile << "文件操作很简单！" << endl;\n        outFile.close();\n    }\n    \n    // 读文件\n    ifstream inFile("test.txt");\n    string line;\n    while (getline(inFile, line)) {\n        cout << line << endl;\n    }\n    inFile.close();\n    \n    return 0;\n}\n*/',
      steps: [
        {
          title: "try-catch-throw 三剑客",
          content: '<p>C++的异常处理机制通过<strong>throw抛出</strong>、<strong>try检测</strong>、<strong>catch捕获</strong>三个关键字协同工作。</p><div class="theory-anim-box"><div class="theory-anim-title">🛡️ 异常处理流程</div><div style="max-width:400px;margin:1rem auto"><div class="t0-fadein" style="animation-delay:0.2s;background:rgba(0,206,201,0.12);border:2px solid rgba(0,206,201,0.3);border-radius:10px;padding:0.7rem;margin-bottom:0.4rem;display:flex;align-items:center;gap:0.5rem"><div style="background:#00cec9;color:#1a2332;width:28px;height:28px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:0.7rem;font-weight:900;flex-shrink:0">try</div><div style="font-size:0.75rem;color:rgba(255,255,255,0.6)">尝试执行可能出错的代码</div></div><div style="text-align:center;font-size:0.8rem;color:rgba(255,255,255,0.2);margin:0.2rem 0">⬇️ 出错了！</div><div class="t0-fadein" style="animation-delay:0.4s;background:rgba(255,152,0,0.12);border:2px solid rgba(255,152,0,0.3);border-radius:10px;padding:0.7rem;margin-bottom:0.4rem;display:flex;align-items:center;gap:0.5rem"><div style="background:#FF9800;color:#1a2332;width:36px;height:28px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:0.6rem;font-weight:900;flex-shrink:0">throw</div><div style="font-size:0.75rem;color:rgba(255,255,255,0.6)">抛出异常对象（如runtime_error）</div></div><div style="text-align:center;font-size:0.8rem;color:rgba(255,255,255,0.2);margin:0.2rem 0">⬇️ 传递给</div><div class="t0-fadein" style="animation-delay:0.6s;background:rgba(105,240,174,0.12);border:2px solid rgba(105,240,174,0.3);border-radius:10px;padding:0.7rem;display:flex;align-items:center;gap:0.5rem"><div style="background:#69F0AE;color:#1a2332;width:36px;height:28px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:0.6rem;font-weight:900;flex-shrink:0">catch</div><div style="font-size:0.75rem;color:rgba(255,255,255,0.6)">捕获并处理异常，程序不会崩溃</div></div></div></div>'
        },
        {
          title: "C++异常体系与RAII",
          content: '<p>C++标准库提供了丰富的异常类层次，<strong>RAII</strong>是C++管理资源的核心理念。</p><div class="theory-anim-box"><div class="theory-anim-title">🏗️ 异常类层次与RAII</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:0.8rem;margin:1rem 0"><div class="t0-fadein" style="animation-delay:0.2s;background:rgba(253,121,168,0.1);border:1px solid rgba(253,121,168,0.3);border-radius:10px;padding:0.8rem"><div style="font-weight:800;color:#fd79a8;font-size:0.8rem;margin-bottom:0.5rem">📋 异常类层次</div><div style="font-size:0.68rem;color:rgba(255,255,255,0.5);line-height:1.8;font-family:monospace">exception<br>├── logic_error<br>│   ├── invalid_argument<br>│   └── out_of_range<br>└── runtime_error<br>&nbsp;&nbsp;&nbsp;&nbsp;├── overflow_error<br>&nbsp;&nbsp;&nbsp;&nbsp;└── range_error</div></div><div class="t0-fadein" style="animation-delay:0.5s;background:rgba(255,152,0,0.1);border:1px solid rgba(255,152,0,0.3);border-radius:10px;padding:0.8rem"><div style="font-weight:800;color:#FF9800;font-size:0.8rem;margin-bottom:0.5rem">🔒 RAII 原则</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.5);line-height:1.7"><strong style="color:rgba(255,255,255,0.7)">R</strong>esource<br><strong style="color:rgba(255,255,255,0.7)">A</strong>cquisition<br><strong style="color:rgba(255,255,255,0.7)">I</strong>s<br><strong style="color:rgba(255,255,255,0.7)">I</strong>nitialization<br><br><span style="font-size:0.65rem;color:rgba(255,255,255,0.4)">在构造函数中获取资源<br>在析构函数中释放资源</span></div></div></div><div class="theory-callout">💡 <strong>RAII</strong>确保即使发生异常，资源也会被正确释放。智能指针（unique_ptr, shared_ptr）就是RAII的最佳实践！</div></div>'
        },
        {
          title: "文件I/O —— 读写文件",
          content: '<p>C++的文件操作使用<strong>fstream</strong>库，支持文本和二进制两种模式。</p><div class="theory-anim-box"><div class="theory-anim-title">📄 C++文件流</div><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:0.6rem;margin:1rem 0"><div class="t0-fadein" style="animation-delay:0.2s;background:rgba(0,206,201,0.1);border:1px solid rgba(0,206,201,0.3);border-radius:10px;padding:0.7rem;text-align:center"><div style="font-size:1.3rem;margin-bottom:0.3rem">📥</div><div style="font-weight:800;color:#00cec9;font-size:0.8rem">ifstream</div><div style="font-size:0.65rem;color:rgba(255,255,255,0.4);margin-top:0.2rem">输入：读文件</div></div><div class="t0-fadein" style="animation-delay:0.4s;background:rgba(253,121,168,0.1);border:1px solid rgba(253,121,168,0.3);border-radius:10px;padding:0.7rem;text-align:center"><div style="font-size:1.3rem;margin-bottom:0.3rem">📤</div><div style="font-weight:800;color:#fd79a8;font-size:0.8rem">ofstream</div><div style="font-size:0.65rem;color:rgba(255,255,255,0.4);margin-top:0.2rem">输出：写文件</div></div><div class="t0-fadein" style="animation-delay:0.6s;background:rgba(255,152,0,0.1);border:1px solid rgba(255,152,0,0.3);border-radius:10px;padding:0.7rem;text-align:center"><div style="font-size:1.3rem;margin-bottom:0.3rem">🔄</div><div style="font-weight:800;color:#FF9800;font-size:0.8rem">fstream</div><div style="font-size:0.65rem;color:rgba(255,255,255,0.4);margin-top:0.2rem">双向：读+写</div></div></div><div style="background:rgba(0,0,0,0.2);border-radius:8px;padding:0.6rem;font-family:monospace;font-size:0.7rem;line-height:1.8"><span style="color:#546e7a">// 安全的文件读取方式</span><br><span style="color:#c792ea">ifstream</span> file(<span style="color:#c3e88d">"data.txt"</span>);<br><span style="color:#c792ea">if</span> (file.is_open()) {<br>&nbsp;&nbsp;<span style="color:#c792ea">string</span> line;<br>&nbsp;&nbsp;<span style="color:#c792ea">while</span> (getline(file, line)) {<br>&nbsp;&nbsp;&nbsp;&nbsp;cout << line << endl;<br>&nbsp;&nbsp;}<br>} <span style="color:#546e7a">// 文件自动关闭(RAII)</span></div></div>'
        }
      ],
      challenge: {
        desc: "概念题：解释为什么RAII比手动释放资源更安全？如果函数中间throw了异常，手动delete会怎样？",
        hint: "如果函数中间抛出异常，手动delete语句可能被跳过导致内存泄漏。RAII通过析构函数保证无论是否异常，资源都会被释放。"
      }
    }
  ]
};

registerChapter('cpp', CHAPTER_V4_CPP7);
