// 卷三 · 数据结构与算法 - 图论
const CHAPTER_V3_GRAPH = {
  chapter: "第五章：图论基础",
  icon: "🕸️",
  lessons: [
    {
      id: "v3-graph-1",
      title: "图的表示与遍历",
      xp: 35,
      code: '# 图的表示与遍历\n\nprint("=== 邻接表表示 ===")\ngraph = {\n    "A": ["B", "C"],\n    "B": ["A", "D", "E"],\n    "C": ["A", "F"],\n    "D": ["B"],\n    "E": ["B", "F"],\n    "F": ["C", "E"]\n}\nfor node, neighbors in graph.items():\n    print(f"  {node} → {neighbors}")\n\n# BFS 广度优先搜索\ndef bfs(graph, start):\n    visited = set()\n    queue = [start]\n    order = []\n    while queue:\n        node = queue.pop(0)\n        if node not in visited:\n            visited.add(node)\n            order.append(node)\n            for neighbor in graph[node]:\n                if neighbor not in visited:\n                    queue.append(neighbor)\n    return order\n\n# DFS 深度优先搜索\ndef dfs(graph, start, visited=None):\n    if visited is None:\n        visited = set()\n    visited.add(start)\n    order = [start]\n    for neighbor in graph[start]:\n        if neighbor not in visited:\n            order.extend(dfs(graph, neighbor, visited))\n    return order\n\nprint(f"\\nBFS从A开始: {bfs(graph, \'A\')}")\nprint(f"DFS从A开始: {dfs(graph, \'A\')}")',
      steps: [
        {
          title: "图：万物的连接",
          content: '<p><strong>图</strong>由<strong>节点（顶点）</strong>和<strong>边</strong>组成，可以表示任何"连接"关系：社交网络、城市路线、网页链接等。</p><div class="theory-anim-box"><div class="theory-anim-title">🕸️ 图的可视化</div><div style="text-align:center;padding:1rem;position:relative;height:180px"><div class="t0-fadein" style="animation-delay:0.2s;position:absolute;left:50%;top:5px;transform:translateX(-50%);width:36px;height:36px;border-radius:50%;background:linear-gradient(135deg,#FF9800,#fdcb6e);display:flex;align-items:center;justify-content:center;font-weight:900;color:#1a2332;font-size:0.85rem">A</div><div class="t0-fadein" style="animation-delay:0.3s;position:absolute;left:20%;top:60px;width:36px;height:36px;border-radius:50%;background:rgba(253,121,168,0.3);border:2px solid #fd79a8;display:flex;align-items:center;justify-content:center;font-weight:800;color:#fd79a8;font-size:0.85rem">B</div><div class="t0-fadein" style="animation-delay:0.4s;position:absolute;right:20%;top:60px;width:36px;height:36px;border-radius:50%;background:rgba(0,206,201,0.3);border:2px solid #00cec9;display:flex;align-items:center;justify-content:center;font-weight:800;color:#00cec9;font-size:0.85rem">C</div><div class="t0-fadein" style="animation-delay:0.5s;position:absolute;left:10%;bottom:10px;width:36px;height:36px;border-radius:50%;background:rgba(253,121,168,0.3);border:2px solid #fd79a8;display:flex;align-items:center;justify-content:center;font-weight:800;color:#fd79a8;font-size:0.85rem">D</div><div class="t0-fadein" style="animation-delay:0.6s;position:absolute;left:50%;bottom:10px;transform:translateX(-50%);width:36px;height:36px;border-radius:50%;background:rgba(105,240,174,0.3);border:2px solid #69F0AE;display:flex;align-items:center;justify-content:center;font-weight:800;color:#69F0AE;font-size:0.85rem">E</div><div class="t0-fadein" style="animation-delay:0.7s;position:absolute;right:10%;bottom:10px;width:36px;height:36px;border-radius:50%;background:rgba(255,171,64,0.3);border:2px solid #FFab40;display:flex;align-items:center;justify-content:center;font-weight:800;color:#FFAB40;font-size:0.85rem">F</div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:0.6rem;margin-top:0.5rem;font-size:0.75rem"><div style="background:rgba(253,121,168,0.08);border-radius:8px;padding:0.5rem;text-align:center"><span style="color:#fd79a8;font-weight:700">BFS</span> 广度优先<div style="font-size:0.65rem;color:rgba(255,255,255,0.4)">一层一层探索，像涟漪</div></div><div style="background:rgba(0,206,201,0.08);border-radius:8px;padding:0.5rem;text-align:center"><span style="color:#00cec9;font-weight:700">DFS</span> 深度优先<div style="font-size:0.65rem;color:rgba(255,255,255,0.4)">一条路走到底再回头</div></div></div></div>'
        },
        {
          title: "BFS vs DFS 的选择",
          content: '<p>BFS和DFS各有所长，选择哪个取决于问题的特点。</p><div class="theory-anim-box"><div class="theory-anim-title">⚖️ BFS vs DFS</div><table style="width:100%;border-collapse:collapse;font-size:0.75rem;margin:0.5rem 0"><tr style="border-bottom:1px solid rgba(255,255,255,0.1)"><th style="padding:0.5rem;text-align:left;color:rgba(255,255,255,0.4)">场景</th><th style="padding:0.5rem;text-align:center;color:#fd79a8;font-weight:700">BFS</th><th style="padding:0.5rem;text-align:center;color:#00cec9;font-weight:700">DFS</th></tr><tr style="border-bottom:1px solid rgba(255,255,255,0.05)"><td style="padding:0.4rem">最短路径</td><td style="padding:0.4rem;text-align:center;color:#69F0AE">✅ 天然支持</td><td style="padding:0.4rem;text-align:center;color:#fd79a8">❌</td></tr><tr style="border-bottom:1px solid rgba(255,255,255,0.05)"><td style="padding:0.4rem">内存消耗</td><td style="padding:0.4rem;text-align:center;color:#fd79a8">较大（队列）</td><td style="padding:0.4rem;text-align:center;color:#69F0AE">较小（栈）</td></tr><tr style="border-bottom:1px solid rgba(255,255,255,0.05)"><td style="padding:0.4rem">找所有解</td><td style="padding:0.4rem;text-align:center;color:#fd79a8">❌</td><td style="padding:0.4rem;text-align:center;color:#69F0AE">✅ 回溯法</td></tr><tr><td style="padding:0.4rem">层级遍历</td><td style="padding:0.4rem;text-align:center;color:#69F0AE">✅ 天然支持</td><td style="padding:0.4rem;text-align:center;color:#fd79a8">❌</td></tr></table><div class="theory-callout">💡 最短路径用BFS，搜索所有解用DFS，这是算法竞赛的经典口诀！</div></div>'
        }
      ],
      challenge: {
        desc: "用BFS找从A到F的最短路径，并打印路径。",
        template: 'graph = {\n    "A": ["B", "C"],\n    "B": ["A", "D", "E"],\n    "C": ["A", "F"],\n    "D": ["B"],\n    "E": ["B", "F"],\n    "F": ["C", "E"]\n}\n# 你的代码：BFS找最短路径',
        check: function(output) { return output.indexOf('A') !== -1 && output.indexOf('F') !== -1; },
        hint: 'graph = {"A": ["B", "C"], "B": ["A", "D", "E"], "C": ["A", "F"], "D": ["B"], "E": ["B", "F"], "F": ["C", "E"]}\nfrom collections import deque\ndef bfs_path(graph, start, end):\n    queue = deque([(start, [start])])\n    visited = {start}\n    while queue:\n        node, path = queue.popleft()\n        if node == end:\n            return path\n        for nb in graph[node]:\n            if nb not in visited:\n                visited.add(nb)\n                queue.append((nb, path + [nb]))\n    return None\npath = bfs_path(graph, "A", "F")\nprint(f"最短路径: {\" → \".join(path)}, 长度: {len(path)-1}")'
      }
    }
  ]
};

registerChapter('dsa', CHAPTER_V3_GRAPH);
