// 卷三 · 数据结构与算法 - 哈希表与堆
const CHAPTER_V3_HASH = {
  chapter: "第三章：哈希表与集合",
  icon: "🔑",
  lessons: [
    {
      id: "v3-hash-1",
      title: "哈希表 —— O(1)查找的秘密",
      xp: 30,
      code: '# 哈希表的工作原理\n\nprint("=== 哈希函数演示 ===")\ndef simple_hash(key, size=10):\n    """简单的哈希函数"""\n    if isinstance(key, str):\n        h = 0\n        for ch in key:\n            h = (h * 31 + ord(ch)) % size\n        return h\n    return key % size\n\n# 演示哈希值分布\nkeys = ["apple", "banana", "cherry", "date", "elderberry", "fig", "grape"]\nprint("哈希表大小: 10")\nfor k in keys:\n    idx = simple_hash(k)\n    print(f"  hash(\"{k}\") = {idx}")\n\n# 手动实现一个简单的哈希表\nprint("\\n=== 简易哈希表 ===")\nclass SimpleHashTable:\n    def __init__(self, size=10):\n        self.size = size\n        self.table = [[] for _ in range(size)]\n    \n    def put(self, key, value):\n        idx = simple_hash(key, self.size)\n        for i, (k, v) in enumerate(self.table[idx]):\n            if k == key:\n                self.table[idx][i] = (key, value)\n                return\n        self.table[idx].append((key, value))\n    \n    def get(self, key):\n        idx = simple_hash(key, self.size)\n        for k, v in self.table[idx]:\n            if k == key:\n                return v\n        return None\n\nht = SimpleHashTable()\nht.put("name", "小王王")\nht.put("age", 10)\nht.put("hobby", "编程")\nprint(f"name: {ht.get(\"name\")}")\nprint(f"age: {ht.get(\"age\")}")\nprint(f"hobby: {ht.get(\"hobby\")}")',
      steps: [
        {
          title: "哈希函数：key到index的映射",
          content: '<p><strong>哈希表</strong>通过<strong>哈希函数</strong>将键映射为数组索引，实现O(1)的查找、插入和删除。</p><div class="theory-anim-box"><div class="theory-anim-title">🔑 哈希函数工作原理</div><div style="display:flex;align-items:center;justify-content:center;gap:1rem;margin:1rem 0;flex-wrap:wrap"><div style="text-align:center"><div style="font-size:0.7rem;color:rgba(255,255,255,0.4);margin-bottom:0.3rem">键 (Key)</div><div class="t0-fadein" style="animation-delay:0.2s;background:rgba(108,92,231,0.15);border:1px solid rgba(108,92,231,0.3);border-radius:8px;padding:0.5rem 1rem;font-weight:700;color:#6c5ce7;font-size:0.85rem">"apple"</div></div><div style="font-size:1.5rem;color:rgba(255,255,255,0.2)">→</div><div style="text-align:center"><div style="font-size:0.7rem;color:rgba(255,255,255,0.4);margin-bottom:0.3rem">哈希函数</div><div class="t0-fadein" style="animation-delay:0.4s;background:rgba(255,152,0,0.15);border:1px solid rgba(255,152,0,0.3);border-radius:8px;padding:0.5rem 1rem;font-weight:700;color:#FF9800;font-size:0.85rem">hash() % 10</div></div><div style="font-size:1.5rem;color:rgba(255,255,255,0.2)">→</div><div style="text-align:center"><div style="font-size:0.7rem;color:rgba(255,255,255,0.4);margin-bottom:0.3rem">索引 (Index)</div><div class="t0-fadein" style="animation-delay:0.6s;background:rgba(0,206,201,0.15);border:1px solid rgba(0,206,201,0.3);border-radius:8px;padding:0.5rem 1rem;font-weight:700;color:#00cec9;font-size:0.85rem">3</div></div></div><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:0.6rem;margin-top:0.8rem;font-size:0.75rem"><div style="background:rgba(0,206,201,0.08);border-radius:8px;padding:0.5rem;text-align:center"><span style="color:#00cec9;font-weight:700">✅ 查找 O(1)</span><div style="font-size:0.65rem;color:rgba(255,255,255,0.4)">直接计算地址</div></div><div style="background:rgba(0,206,201,0.08);border-radius:8px;padding:0.5rem;text-align:center"><span style="color:#00cec9;font-weight:700">✅ 插入 O(1)</span><div style="font-size:0.65rem;color:rgba(255,255,255,0.4)">计算后直接存放</div></div></div></div>'
        },
        {
          title: "哈希冲突与解决方案",
          content: '<p>当两个不同的键计算出相同的索引时，就发生了<strong>哈希冲突</strong>。常见的解决方案有<strong>链地址法</strong>和<strong>开放寻址法</strong>。</p><div class="theory-anim-box"><div class="theory-anim-title">💥 哈希冲突处理</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin:1rem 0"><div class="t0-fadein" style="animation-delay:0.3s;background:rgba(108,92,231,0.1);border:1px solid rgba(108,92,231,0.3);border-radius:10px;padding:0.8rem"><div style="font-weight:800;color:#6c5ce7;font-size:0.85rem;margin-bottom:0.5rem">🔗 链地址法</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.5);line-height:1.8">每个槽位存一个链表：<br>[0] → None<br>[1] → "apple"→"fig"→None<br>[2] → "banana"→None<br>[3] → None<br>冲突元素追加到链表尾</div></div><div class="t0-fadein" style="animation-delay:0.6s;background:rgba(0,206,201,0.1);border:1px solid rgba(0,206,201,0.3);border-radius:10px;padding:0.8rem"><div style="font-weight:800;color:#00cec9;font-size:0.85rem;margin-bottom:0.5rem">📍 开放寻址法</div><div style="font-size:0.7rem;color:rgba(255,255,255,0.5);line-height:1.8">冲突后找下一个空位：<br>[1] ← "apple" (首选)<br>[2] ← "fig" (冲突，后移)<br><br>线性探测、二次探测<br>双重哈希</div></div></div><div class="theory-callout">💡 Python的dict就是哈希表！它使用开放寻址法，负载因子超过2/3时自动扩容。</div></div>'
        }
      ],
      challenge: {
        desc: "实现一个单词频率计数器：读入一段文本，统计每个单词出现的次数。",
        template: 'text = "the cat sat on the mat the cat"\nwords = text.split()\n# 用字典统计词频\n# 你的代码',
        check: function(output) { return output.indexOf('the') !== -1 && output.indexOf('3') !== -1; },
        hint: 'text = "the cat sat on the mat the cat"\nwords = text.split()\nfreq = {}\nfor w in words:\n    freq[w] = freq.get(w, 0) + 1\nfor word, count in sorted(freq.items(), key=lambda x: -x[1]):\n    print(f"{word}: {count}")'
      }
    },
    {
      id: "v3-hash-2",
      title: "集合操作与布隆过滤器",
      xp: 35,
      code: '# Python集合(set)操作演示\n\n# 集合基本操作\nfruits_a = {"苹果", "香蕉", "橘子", "葡萄"}\nfruits_b = {"橘子", "葡萄", "西瓜", "芒果"}\n\nprint("=== 集合运算 ===")\nprint(f"A = {fruits_a}")\nprint(f"B = {fruits_b}")\nprint(f"交集(A∩B): {fruits_a & fruits_b}")\nprint(f"并集(A∪B): {fruits_a | fruits_b}")\nprint(f"差集(A-B): {fruits_a - fruits_b}")\nprint(f"对称差集: {fruits_a ^ fruits_b}")\n\n# 简易布隆过滤器\nprint("\\n=== 布隆过滤器 ===")\nclass BloomFilter:\n    def __init__(self, size=20):\n        self.bits = [0] * size\n        self.size = size\n    \n    def _hashes(self, item):\n        h1 = hash(item) % self.size\n        h2 = (hash(item) * 31 + 7) % self.size\n        return [abs(h1), abs(h2)]\n    \n    def add(self, item):\n        for h in self._hashes(item):\n            self.bits[h] = 1\n        print(f"  添加 \\"{item}\\" → 位: {self._hashes(item)}")\n    \n    def might_contain(self, item):\n        return all(self.bits[h] for h in self._hashes(item))\n\nbf = BloomFilter(20)\nfor w in ["apple", "banana", "cherry"]:\n    bf.add(w)\n\nprint(f"\\n检测:")\nfor w in ["apple", "grape", "banana", "mango"]:\n    result = bf.might_contain(w)\n    print(f"  \\"{w}\\" → {\"可能存在\" if result else \"一定不存在\"}")',
      steps: [
        {
          title: "集合：数学思维的编程实现",
          content: '<p><strong>集合(Set)</strong>是基于哈希表的数据结构，存储不重复的元素，支持交、并、差等数学运算。</p><div class="theory-anim-box"><div class="theory-anim-title">🔢 集合运算可视化</div><div style="display:flex;justify-content:center;align-items:center;gap:0.5rem;margin:1rem 0;flex-wrap:wrap"><div class="t0-fadein" style="animation-delay:0.2s;width:110px;height:110px;border-radius:50%;border:2px solid rgba(108,92,231,0.4);background:rgba(108,92,231,0.1);display:flex;align-items:center;justify-content:center;position:relative;margin-right:-25px;z-index:1"><div style="text-align:center;font-size:0.65rem;color:#6c5ce7;font-weight:700;position:absolute;left:15px">🍎🍌<br>集合A</div></div><div class="t0-fadein" style="animation-delay:0.4s;width:110px;height:110px;border-radius:50%;border:2px solid rgba(0,206,201,0.4);background:rgba(0,206,201,0.08);display:flex;align-items:center;justify-content:center;position:relative;z-index:1"><div style="text-align:center;font-size:0.65rem;color:#00cec9;font-weight:700;position:absolute;right:15px">🍉🥭<br>集合B</div><div style="position:absolute;left:-5px;text-align:center;font-size:0.6rem;color:#FF9800;font-weight:700">🍊🍇<br>A∩B</div></div></div><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:0.5rem;margin:0.8rem 0"><div style="background:rgba(108,92,231,0.08);border:1px solid rgba(108,92,231,0.2);border-radius:8px;padding:0.4rem;text-align:center;font-size:0.7rem"><span style="color:#6c5ce7;font-weight:700">A & B</span> → 交集</div><div style="background:rgba(0,206,201,0.08);border:1px solid rgba(0,206,201,0.2);border-radius:8px;padding:0.4rem;text-align:center;font-size:0.7rem"><span style="color:#00cec9;font-weight:700">A | B</span> → 并集</div><div style="background:rgba(255,152,0,0.08);border:1px solid rgba(255,152,0,0.2);border-radius:8px;padding:0.4rem;text-align:center;font-size:0.7rem"><span style="color:#FF9800;font-weight:700">A - B</span> → 差集</div><div style="background:rgba(253,121,168,0.08);border:1px solid rgba(253,121,168,0.2);border-radius:8px;padding:0.4rem;text-align:center;font-size:0.7rem"><span style="color:#fd79a8;font-weight:700">A ^ B</span> → 对称差</div></div></div>'
        },
        {
          title: "布隆过滤器：空间换时间的魔法",
          content: '<p><strong>布隆过滤器</strong>用极少的内存快速判断一个元素"<strong>一定不存在</strong>"或"<strong>可能存在</strong>"。广泛用于垃圾邮件过滤、缓存穿透防护等场景。</p><div class="theory-anim-box"><div class="theory-anim-title">🌸 布隆过滤器原理</div><div style="margin:1rem 0"><div style="font-size:0.72rem;color:rgba(255,255,255,0.5);margin-bottom:0.5rem;text-align:center">添加 "apple" → hash1=3, hash2=7</div><div style="display:flex;gap:0.15rem;justify-content:center;flex-wrap:wrap;margin-bottom:0.5rem" id="bloomBits">' +
          (function(){var h='';for(var i=0;i<16;i++){var active=i===3||i===7;h+='<div style="width:28px;height:28px;border-radius:4px;display:flex;align-items:center;justify-content:center;font-size:0.65rem;font-weight:700;font-family:monospace;'+(active?'background:rgba(255,152,0,0.3);border:1px solid rgba(255,152,0,0.5);color:#FF9800':'background:rgba(255,255,255,0.05);border:1px solid rgba(255,255,255,0.1);color:rgba(255,255,255,0.3)')+'">'+( active?'1':'0')+'</div>';}return h;})()
          + '</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:0.5rem;margin-top:0.8rem"><div style="background:rgba(105,240,174,0.1);border:1px solid rgba(105,240,174,0.25);border-radius:8px;padding:0.5rem;text-align:center"><div style="font-weight:700;color:#69F0AE;font-size:0.75rem">查 "apple"</div><div style="font-size:0.65rem;color:rgba(255,255,255,0.4);margin-top:0.2rem">位3✅ 位7✅ → 可能存在</div></div><div style="background:rgba(253,121,168,0.1);border:1px solid rgba(253,121,168,0.25);border-radius:8px;padding:0.5rem;text-align:center"><div style="font-weight:700;color:#fd79a8;font-size:0.75rem">查 "grape"</div><div style="font-size:0.65rem;color:rgba(255,255,255,0.4);margin-top:0.2rem">位5❌ → 一定不存在</div></div></div></div><div class="theory-callout">💡 布隆过滤器的特点：<strong>可能误判存在</strong>（假阳性），但<strong>绝不会误判不存在</strong>（无假阴性）。Redis、Chrome、Cassandra 都在用它！</div></div>'
        }
      ],
      challenge: {
        desc: "用Python的set实现：给定两个班级的学生名单，找出①只在A班的学生 ②两个班都有的学生 ③所有学生",
        template: 'class_a = {"小明", "小红", "小刚", "小李"}\nclass_b = {"小红", "小刚", "小王", "小张"}\n# 你的代码',
        check: function(output) { return output.indexOf('小明') !== -1; },
        hint: 'class_a = {"小明", "小红", "小刚", "小李"}\nclass_b = {"小红", "小刚", "小王", "小张"}\nprint(f"只在A班: {class_a - class_b}")\nprint(f"两班都有: {class_a & class_b}")\nprint(f"所有学生: {class_a | class_b}")'
      }
    }
  ]
};

registerChapter('dsa', CHAPTER_V3_HASH);
