// 自动拆分：按章节维护作业题库
(function() {
  'use strict';

  window.HOMEWORK_BANK = window.HOMEWORK_BANK || {};
  Object.assign(window.HOMEWORK_BANK, {
// ============ 第十五章：IO编程 ============
"15-1": [
  {desc:"模拟CSV文件解析姓名和分数", template:'csv_data = "小明,95\\n小红,88\\n小刚,92"\n', hint:'csv_data = "小明,95\\n小红,88\\n小刚,92"\nfor line in csv_data.split("\\n"):\n    name, score = line.split(",")\n    print(f"{name}: {score}分")', check:function(o){return o.indexOf("小明")!==-1 && o.indexOf("分")!==-1;}},
  {desc:"模拟写文件并统计行数", template:'text = "Line1\\nLine2\\nLine3\\nLine4"\n', hint:'text = "Line1\\nLine2\\nLine3\\nLine4"\nlines = text.split("\\n")\nprint(f"共{len(lines)}行")\nfor i, line in enumerate(lines, 1):\n    print(f"  {i}: {line}")', check:function(o){return o.indexOf("共4行")!==-1;}},
  {desc:"用 split 和 strip 清洗数据", template:'data = "  apple , banana ,  cherry  "\n', hint:'data = "  apple , banana ,  cherry  "\nclean = [x.strip() for x in data.split(",")]\nprint(clean)', check:function(o){return o.indexOf("apple")!==-1;}},
  {desc:"模拟逐行处理大文件", template:'# 逐行处理\n', hint:'text = "\\n".join([f"第{i}行数据" for i in range(1, 11)])\nfor i, line in enumerate(text.split("\\n"), 1):\n    print(f"处理: {line}")', check:function(o){return o.indexOf("处理")!==-1;}},
  {desc:"将列表数据格式化为表格输出", template:'data = [("姓名","分数"),("小明",95),("小红",88)]\n', hint:'data = [("姓名","分数"),("小明",95),("小红",88)]\nfor name, score in data:\n    print(f"{str(name):^8}{str(score):^8}")', check:function(o){return o.indexOf("小明")!==-1;}},
  {desc:"解析多字段CSV数据", template:'csv = "姓名,语文,数学,英语\\n小明,90,95,88\\n小红,85,92,96"\n', hint:'csv = "姓名,语文,数学,英语\\n小明,90,95,88\\n小红,85,92,96"\nlines = csv.split("\\n")\nheaders = lines[0].split(",")\nfor line in lines[1:]:\n    values = line.split(",")\n    for h, v in zip(headers, values):\n        print(f"  {h}: {v}", end="")\n    print()', check:function(o){return o.indexOf("语文")!==-1;}},
  {desc:"实现简单的文件搜索（在文本中查找关键词）", template:'text = "Python很强大\\nJava也不错\\nPython是首选\\n我喜欢编程"\n', hint:'text = "Python很强大\\nJava也不错\\nPython是首选\\n我喜欢编程"\nkeyword = "Python"\nfor i, line in enumerate(text.split("\\n"), 1):\n    if keyword in line:\n        print(f"第{i}行: {line}")', check:function(o){return o.indexOf("Python")!==-1;}},
  {desc:"合并多段文本数据", template:'parts = ["Hello ", "World ", "from ", "Python!"]\n', hint:'parts = ["Hello ", "World ", "from ", "Python!"]\nresult = "".join(parts)\nprint(result)\nprint(f"总长度: {len(result)}")', check:function(o){return o.indexOf("Hello World")!==-1;}},
  {desc:"实现文本行号添加器", template:'text = "苹果\\n香蕉\\n橘子\\n葡萄\\n西瓜"\n', hint:'text = "苹果\\n香蕉\\n橘子\\n葡萄\\n西瓜"\nfor i, line in enumerate(text.split("\\n"), 1):\n    print(f"{i:3d}| {line}")', check:function(o){return o.indexOf("1|")!==-1 || o.indexOf("  1|")!==-1;}},
  {desc:"实现简单的文本统计（字数、行数、最长行）", template:'text = "Hello World\\nPython Programming\\nAI is the future of technology"\n', hint:'text = "Hello World\\nPython Programming\\nAI is the future of technology"\nlines = text.split("\\n")\nwords = text.split()\nprint(f"行数: {len(lines)}")\nprint(f"词数: {len(words)}")\nlongest = max(lines, key=len)\nprint(f"最长行: {longest}")', check:function(o){return o.indexOf("行数")!==-1;}}
],
"15-2": [
  {desc:"用json.dumps和json.loads序列化和反序列化", template:'import json\n', hint:'import json\nstudents = {"class":"五年级","students":[{"name":"小明","score":95},{"name":"小红","score":88}]}\njson_str = json.dumps(students, ensure_ascii=False, indent=2)\nprint(json_str)\ndata = json.loads(json_str)\nfor s in data["students"]:\n    print(f"{s[\"name\"]}: {s[\"score\"]}分")', check:function(o){return o.indexOf("name")!==-1;}},
  {desc:"将Python字典转为JSON格式字符串", template:'import json\n', hint:'import json\nd = {"name":"Alice","age":25,"hobbies":["reading","coding"]}\nprint(json.dumps(d, indent=2))', check:function(o){return o.indexOf("Alice")!==-1;}},
  {desc:"处理JSON中的中文（ensure_ascii=False）", template:'import json\n', hint:'import json\ndata = {"姓名":"小明","爱好":["编程","阅读"]}\nprint(json.dumps(data, ensure_ascii=False, indent=2))', check:function(o){return o.indexOf("小明")!==-1;}},
  {desc:"解析嵌套JSON数据", template:'import json\n', hint:'import json\njson_str = \'{"school":"XX小学","classes":[{"name":"一班","count":30},{"name":"二班","count":28}]}\'\ndata = json.loads(json_str)\nprint(f"学校: {data[\"school\"]}")\nfor c in data["classes"]:\n    print(f"  {c[\"name\"]}: {c[\"count\"]}人")', check:function(o){return o.indexOf("学校")!==-1;}},
  {desc:"将列表数据转为JSON并还原", template:'import json\n', hint:'import json\nitems = [1, "hello", True, None, [2,3]]\njson_str = json.dumps(items)\nprint(f"JSON: {json_str}")\nrestored = json.loads(json_str)\nprint(f"还原: {restored}")\nprint(f"相同: {items == restored}")', check:function(o){return o.indexOf("JSON")!==-1;}},
  {desc:"用json处理配置数据", template:'import json\n', hint:'import json\nconfig = {"debug":True,"port":8080,"db":{"host":"localhost","name":"mydb"}}\njson_str = json.dumps(config, indent=2)\nprint(json_str)\nloaded = json.loads(json_str)\nprint(f"端口: {loaded[\"port\"]}")\nprint(f"数据库: {loaded[\"db\"][\"host\"]}")', check:function(o){return o.indexOf("8080")!==-1;}},
  {desc:"用json美化输出复杂数据", template:'import json\n', hint:'import json\ndata = {"users":[{"id":1,"name":"A","roles":["admin","user"]},{"id":2,"name":"B","roles":["user"]}]}\nprint(json.dumps(data, indent=4, ensure_ascii=False))', check:function(o){return o.indexOf("admin")!==-1;}},
  {desc:"用json.dumps的default参数处理特殊类型", template:'import json\n', hint:'import json\nclass Point:\n    def __init__(self, x, y): self.x=x; self.y=y\ndef encoder(obj):\n    if isinstance(obj, Point): return {"x":obj.x,"y":obj.y}\n    raise TypeError(f"不支持的类型: {type(obj)}")\nresult = json.dumps({"point": Point(3,4)}, default=encoder)\nprint(result)', check:function(o){return o.indexOf('"x"')!==-1;}},
  {desc:"对比json.dumps和str()的区别", template:'import json\n', hint:'import json\ndata = {"name":"test","value":True,"nothing":None}\nprint(f"str():  {str(data)}")\nprint(f"json(): {json.dumps(data)}")\nprint("注意: True→true, None→null")', check:function(o){return o.indexOf("true")!==-1;}},
  {desc:"实现简单的数据持久化（存取用户配置）", template:'import json\n', hint:'import json\ndef save_config(config):\n    json_str = json.dumps(config, indent=2)\n    print(f"保存: {json_str}")\n    return json_str\ndef load_config(json_str):\n    return json.loads(json_str)\nconfig = {"theme":"dark","font_size":14,"lang":"zh"}\nsaved = save_config(config)\nloaded = load_config(saved)\nprint(f"加载: theme={loaded[\"theme\"]}")', check:function(o){return o.indexOf("保存")!==-1;}}
],
"15-3": [
  {desc:"用StringIO模拟写入和读取", template:'# StringIO\n', hint:'class StringIO:\n    def __init__(self, text=""): self.data = text\n    def write(self, s): self.data += s\n    def getvalue(self): return self.data\n    def readlines(self): return self.data.split("\\n")\nf = StringIO()\nf.write("苹果\\n")\nf.write("香蕉\\n")\nf.write("橘子")\nfor line in StringIO(f.getvalue()).readlines():\n    if line: print(line)', check:function(o){return o.trim().split("\n").length>=2;}},
  {desc:"用StringIO收集多次print的输出", template:'# 收集输出\n', hint:'output = []\ndef my_print(*args):\n    output.append(" ".join(str(a) for a in args))\nmy_print("Hello")\nmy_print("World")\nmy_print("Python")\nresult = "\\n".join(output)\nprint(result)\nprint(f"共{len(output)}行")', check:function(o){return o.indexOf("共3行")!==-1;}},
  {desc:"模拟内存中的日志系统", template:'# 内存日志\n', hint:'class MemoryLog:\n    def __init__(self): self.logs = []\n    def write(self, msg): self.logs.append(msg)\n    def dump(self): return "\\n".join(self.logs)\nlog = MemoryLog()\nlog.write("[INFO] 启动")\nlog.write("[WARN] 注意")\nlog.write("[ERROR] 出错")\nprint(log.dump())', check:function(o){return o.indexOf("[INFO]")!==-1;}},
  {desc:"用字符串缓冲区构建HTML", template:'# HTML构建\n', hint:'parts = []\nparts.append("<html>")\nparts.append("<body>")\nparts.append("<h1>Hello</h1>")\nparts.append("<p>World</p>")\nparts.append("</body>")\nparts.append("</html>")\nhtml = "\\n".join(parts)\nprint(html)', check:function(o){return o.indexOf("<html>")!==-1;}},
  {desc:"模拟从内存读取CSV数据", template:'# 内存CSV\n', hint:'csv_content = "name,age,city\\nAlice,25,Beijing\\nBob,30,Shanghai"\nlines = csv_content.split("\\n")\nheaders = lines[0].split(",")\nfor line in lines[1:]:\n    values = line.split(",")\n    record = dict(zip(headers, values))\n    print(record)', check:function(o){return o.indexOf("Alice")!==-1;}},
  {desc:"实现一个字符串流过滤器", template:'# 过滤器\n', hint:'def filter_lines(text, keyword):\n    result = []\n    for line in text.split("\\n"):\n        if keyword in line:\n            result.append(line)\n    return "\\n".join(result)\ntext = "apple is red\\nbanana is yellow\\napple pie\\ncherry"\nprint(filter_lines(text, "apple"))', check:function(o){return o.indexOf("apple")!==-1;}},
  {desc:"用列表模拟文件的seek操作", template:'# 模拟seek\n', hint:'class MemFile:\n    def __init__(self, data): self.data = data; self.pos = 0\n    def read(self, n=-1):\n        if n < 0: result = self.data[self.pos:]; self.pos = len(self.data)\n        else: result = self.data[self.pos:self.pos+n]; self.pos += n\n        return result\n    def seek(self, pos): self.pos = pos\nf = MemFile("Hello World Python")\nprint(f.read(5))\nf.seek(6)\nprint(f.read(5))', check:function(o){return o.indexOf("Hello")!==-1 && o.indexOf("World")!==-1;}},
  {desc:"实现内存中的键值存储", template:'# 键值存储\n', hint:'class MemoryStore:\n    def __init__(self): self.data = {}\n    def put(self, key, val): self.data[key] = val\n    def get(self, key): return self.data.get(key)\n    def dump(self):\n        import json\n        return json.dumps(self.data, ensure_ascii=False)\nstore = MemoryStore()\nstore.put("name", "小明")\nstore.put("age", 10)\nprint(store.dump())\nprint(store.get("name"))', check:function(o){return o.indexOf("小明")!==-1;}},
  {desc:"模拟文件的追加和读取", template:'# 追加模式\n', hint:'buffer = ""\nbuffer += "第一行\\n"\nbuffer += "第二行\\n"\nbuffer += "第三行\\n"\nprint("内容:")\nprint(buffer)\nprint(f"共{len(buffer.strip().split(chr(10)))}行")', check:function(o){return o.indexOf("第一行")!==-1;}},
  {desc:"综合：用内存流实现一个简单的模板引擎", template:'# 模板引擎\n', hint:'def render(template, data):\n    result = template\n    for key, val in data.items():\n        result = result.replace("{{" + key + "}}", str(val))\n    return result\ntpl = "你好，{{name}}！你今年{{age}}岁了。"\nprint(render(tpl, {"name":"小明","age":10}))', check:function(o){return o.indexOf("小明")!==-1 && o.indexOf("10岁")!==-1;}}
],
  });
})();
