// 自动拆分：按章节维护作业题库
(function() {
  'use strict';

  window.HOMEWORK_BANK = window.HOMEWORK_BANK || {};
  Object.assign(window.HOMEWORK_BANK, {
// ============ 第十二章：面向对象编程 ============
"12-1": [
  {desc:"创建Pet类，有name和species属性，speak()方法", template:'# Pet类\n', hint:'class Pet:\n    def __init__(self, name, species):\n        self.name = name\n        self.species = species\n    def speak(self):\n        print(f"我是{self.name}，我是一只{self.species}")\nPet("咪咪","猫").speak()', check:function(o){return o.indexOf("我是")!==-1;}},
  {desc:"创建Student类：name、age、score属性和grade()方法", template:'# Student类\n', hint:'class Student:\n    def __init__(self, name, age, score):\n        self.name = name\n        self.age = age\n        self.score = score\n    def grade(self):\n        if self.score >= 90: return "优秀"\n        elif self.score >= 60: return "及格"\n        return "不及格"\ns = Student("小明", 10, 95)\nprint(f"{s.name}: {s.grade()}")', check:function(o){return o.indexOf("优秀")!==-1;}},
  {desc:"创建Rectangle类：宽、高属性，area()和perimeter()方法", template:'# Rectangle类\n', hint:'class Rectangle:\n    def __init__(self, w, h):\n        self.w = w\n        self.h = h\n    def area(self): return self.w * self.h\n    def perimeter(self): return 2*(self.w+self.h)\nr = Rectangle(5, 3)\nprint(f"面积:{r.area()} 周长:{r.perimeter()}")', check:function(o){return o.indexOf("15")!==-1 && o.indexOf("16")!==-1;}},
  {desc:"创建BankAccount类：存款、取款、查余额", template:'# 银行账户\n', hint:'class BankAccount:\n    def __init__(self, owner, balance=0):\n        self.owner = owner\n        self.balance = balance\n    def deposit(self, amount):\n        self.balance += amount\n        print(f"存入{amount}，余额:{self.balance}")\n    def withdraw(self, amount):\n        if amount > self.balance:\n            print("余额不足")\n        else:\n            self.balance -= amount\n            print(f"取出{amount}，余额:{self.balance}")\nacc = BankAccount("小明", 100)\nacc.deposit(50)\nacc.withdraw(30)', check:function(o){return o.indexOf("余额")!==-1;}},
  {desc:"创建一个Book类并实现__str__方法", template:'# Book类\n', hint:'class Book:\n    def __init__(self, title, author, pages):\n        self.title = title\n        self.author = author\n        self.pages = pages\n    def __str__(self):\n        return f"《{self.title}》- {self.author} ({self.pages}页)"\nb = Book("Python入门", "张三", 200)\nprint(b)', check:function(o){return o.indexOf("《")!==-1;}},
  {desc:"创建一个Counter类，支持increment、decrement、reset", template:'# Counter类\n', hint:'class Counter:\n    def __init__(self):\n        self.count = 0\n    def increment(self): self.count += 1\n    def decrement(self): self.count -= 1\n    def reset(self): self.count = 0\nc = Counter()\nfor _ in range(5): c.increment()\nprint(c.count)\nc.decrement()\nprint(c.count)', check:function(o){return o.indexOf("5")!==-1 && o.indexOf("4")!==-1;}},
  {desc:"创建一个Stack类（后进先出）", template:'# 栈\n', hint:'class Stack:\n    def __init__(self): self.items = []\n    def push(self, item): self.items.append(item)\n    def pop(self): return self.items.pop() if self.items else None\n    def peek(self): return self.items[-1] if self.items else None\n    def size(self): return len(self.items)\ns = Stack()\nfor x in [1,2,3]: s.push(x)\nprint(s.pop())\nprint(s.peek())\nprint(s.size())', check:function(o){return o.indexOf("3")!==-1;}},
  {desc:"创建Temperature类，支持摄氏和华氏互转", template:'# Temperature\n', hint:'class Temperature:\n    def __init__(self, celsius):\n        self.celsius = celsius\n    def to_fahrenheit(self):\n        return self.celsius * 9/5 + 32\n    def from_fahrenheit(f):\n        return Temperature((f-32) * 5/9)\nt = Temperature(100)\nprint(f"{t.celsius}°C = {t.to_fahrenheit()}°F")', check:function(o){return o.indexOf("212")!==-1;}},
  {desc:"创建一个TodoList类：添加、删除、显示待办事项", template:'# TodoList\n', hint:'class TodoList:\n    def __init__(self): self.items = []\n    def add(self, task):\n        self.items.append({"task":task,"done":False})\n    def complete(self, idx):\n        self.items[idx]["done"] = True\n    def show(self):\n        for i, item in enumerate(self.items):\n            status = "✅" if item["done"] else "⬜"\n            print(f"{i+1}. {status} {item[\"task\"]}")\ntodo = TodoList()\ntodo.add("学Python")\ntodo.add("做作业")\ntodo.complete(0)\ntodo.show()', check:function(o){return o.indexOf("✅")!==-1;}},
  {desc:"创建一个Dice类，支持投掷和统计", template:'import random\n', hint:'import random\nclass Dice:\n    def __init__(self, sides=6):\n        self.sides = sides\n        self.history = []\n    def roll(self):\n        result = random.randint(1, self.sides)\n        self.history.append(result)\n        return result\n    def stats(self):\n        if not self.history: return\n        print(f"投了{len(self.history)}次")\n        print(f"平均: {sum(self.history)/len(self.history):.1f}")\nd = Dice()\nfor _ in range(10): d.roll()\nd.stats()', check:function(o){return o.indexOf("投了")!==-1;}}
],
"12-2": [
  {desc:"创建Vehicle父类和Car、Bike子类，各有不同describe()", template:'# 继承\n', hint:'class Vehicle:\n    def __init__(self, name): self.name = name\nclass Car(Vehicle):\n    def describe(self): print(f"汽车{self.name}，4轮")\nclass Bike(Vehicle):\n    def describe(self): print(f"自行车{self.name}，2轮")\nfor v in [Car("宝马"), Bike("凤凰")]: v.describe()', check:function(o){return o.indexOf("轮")!==-1;}},
  {desc:"创建Shape基类和Circle、Square子类，各有area()", template:'# 形状继承\n', hint:'class Shape:\n    def area(self): return 0\nclass Circle(Shape):\n    def __init__(self, r): self.r = r\n    def area(self): return 3.14*self.r**2\nclass Square(Shape):\n    def __init__(self, s): self.s = s\n    def area(self): return self.s**2\nfor s in [Circle(5), Square(4)]:\n    print(f"{type(s).__name__}: {s.area()}")', check:function(o){return o.indexOf("78.5")!==-1;}},
  {desc:"用super()调用父类方法", template:'# super()\n', hint:'class Animal:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return f"我是{self.name}"\nclass Dog(Animal):\n    def speak(self):\n        return super().speak() + "，汪汪！"\nd = Dog("旺财")\nprint(d.speak())', check:function(o){return o.indexOf("汪汪")!==-1;}},
  {desc:"用isinstance检查继承关系", template:'# isinstance\n', hint:'class A: pass\nclass B(A): pass\nclass C(B): pass\nc = C()\nprint(isinstance(c, C))\nprint(isinstance(c, B))\nprint(isinstance(c, A))', check:function(o){return o.indexOf("True")!==-1;}},
  {desc:"多态演示：不同动物的speak()方法", template:'# 多态\n', hint:'class Cat:\n    def speak(self): return "喵~"\nclass Dog:\n    def speak(self): return "汪!"\nclass Duck:\n    def speak(self): return "嘎嘎"\nfor animal in [Cat(), Dog(), Duck()]:\n    print(animal.speak())', check:function(o){return o.indexOf("喵")!==-1 && o.indexOf("汪")!==-1;}},
  {desc:"子类扩展父类功能（添加新方法和属性）", template:'# 扩展功能\n', hint:'class Person:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\nclass Student(Person):\n    def __init__(self, name, age, grade):\n        super().__init__(name, age)\n        self.grade = grade\n    def info(self):\n        print(f"{self.name}, {self.age}岁, {self.grade}年级")\nStudent("小明", 10, 4).info()', check:function(o){return o.indexOf("年级")!==-1;}},
  {desc:"方法重写：子类覆盖父类的同名方法", template:'# 方法重写\n', hint:'class Logger:\n    def log(self, msg): print(f"[LOG] {msg}")\nclass ColorLogger(Logger):\n    def log(self, msg): print(f"🔵 {msg}")\nLogger().log("普通日志")\nColorLogger().log("彩色日志")', check:function(o){return o.indexOf("🔵")!==-1;}},
  {desc:"创建一个Employee和Manager的继承体系", template:'# 员工体系\n', hint:'class Employee:\n    def __init__(self, name, salary):\n        self.name = name\n        self.salary = salary\n    def info(self):\n        print(f"{self.name}: {self.salary}元/月")\nclass Manager(Employee):\n    def __init__(self, name, salary, team_size):\n        super().__init__(name, salary)\n        self.team_size = team_size\n    def info(self):\n        super().info()\n        print(f"  管理{self.team_size}人")\nManager("张总", 20000, 10).info()', check:function(o){return o.indexOf("管理")!==-1;}},
  {desc:"用继承实现一个简单的游戏角色系统", template:'# 游戏角色\n', hint:'class Character:\n    def __init__(self, name, hp):\n        self.name = name\n        self.hp = hp\n    def attack(self, other):\n        dmg = 10\n        other.hp -= dmg\n        print(f"{self.name}攻击{other.name}，造成{dmg}伤害")\nclass Warrior(Character):\n    def attack(self, other):\n        dmg = 20\n        other.hp -= dmg\n        print(f"战士{self.name}猛击{other.name}，造成{dmg}伤害")\nw = Warrior("勇者", 100)\nm = Character("怪物", 50)\nw.attack(m)\nprint(f"{m.name}剩余HP: {m.hp}")', check:function(o){return o.indexOf("伤害")!==-1;}},
  {desc:"用抽象概念实现一个支付系统（现金支付、银行卡支付）", template:'# 支付系统\n', hint:'class Payment:\n    def pay(self, amount): pass\nclass CashPayment(Payment):\n    def pay(self, amount): print(f"现金支付{amount}元")\nclass CardPayment(Payment):\n    def __init__(self, card_no): self.card = card_no\n    def pay(self, amount): print(f"银行卡{self.card}支付{amount}元")\nfor p in [CashPayment(), CardPayment("****1234")]:\n    p.pay(100)', check:function(o){return o.indexOf("支付")!==-1;}}
],
"12-3": [
  {desc:"创建Score类，私有属性，set_score验证0-100", template:'# 访问限制\n', hint:'class Score:\n    def __init__(self): self.__score = 0\n    def set_score(self, val):\n        if 0 <= val <= 100: self.__score = val\n        else: print("分数必须0-100")\n    def get_score(self): return self.__score\ns = Score()\ns.set_score(95)\nprint(s.get_score())\ns.set_score(150)', check:function(o){return o.indexOf("95")!==-1;}},
  {desc:"演示私有属性无法从外部直接访问", template:'# 私有属性\n', hint:'class Secret:\n    def __init__(self):\n        self.__password = "123456"\n    def check(self, pwd):\n        return pwd == self.__password\ns = Secret()\nprint(s.check("123456"))\ntry:\n    print(s.__password)\nexcept AttributeError:\n    print("无法直接访问私有属性")', check:function(o){return o.indexOf("无法")!==-1;}},
  {desc:"用property实现只读属性", template:'# 只读属性\n', hint:'class Circle:\n    def __init__(self, r): self._r = r\n    @property\n    def area(self): return 3.14 * self._r ** 2\nc = Circle(5)\nprint(f"面积: {c.area}")\ntry:\n    c.area = 100\nexcept AttributeError:\n    print("area是只读的")', check:function(o){return o.indexOf("面积")!==-1;}},
  {desc:"实现一个安全的密码类（只能设置不能读取原文）", template:'# 安全密码\n', hint:'class Password:\n    def __init__(self): self.__pwd = ""\n    def set_password(self, pwd):\n        self.__pwd = pwd\n        print("密码已设置")\n    def verify(self, pwd):\n        return pwd == self.__pwd\np = Password()\np.set_password("abc123")\nprint(p.verify("abc123"))\nprint(p.verify("wrong"))', check:function(o){return o.indexOf("True")!==-1 && o.indexOf("False")!==-1;}},
  {desc:"用getter和setter控制属性值范围", template:'# getter/setter\n', hint:'class Temperature:\n    def __init__(self): self.__celsius = 0\n    def get_celsius(self): return self.__celsius\n    def set_celsius(self, val):\n        if val < -273.15:\n            print("温度不能低于绝对零度")\n        else:\n            self.__celsius = val\nt = Temperature()\nt.set_celsius(25)\nprint(t.get_celsius())\nt.set_celsius(-300)', check:function(o){return o.indexOf("25")!==-1 && o.indexOf("绝对零度")!==-1;}},
  {desc:"创建一个类，演示name mangling（名称改编）", template:'# 名称改编\n', hint:'class MyClass:\n    def __init__(self):\n        self.__secret = 42\nc = MyClass()\nprint(c._MyClass__secret)\nprint("通过名称改编可以访问，但不推荐")', check:function(o){return o.indexOf("42")!==-1;}},
  {desc:"实现一个有最大容量限制的列表类", template:'# 限容列表\n', hint:'class LimitedList:\n    def __init__(self, max_size):\n        self.__items = []\n        self.__max = max_size\n    def add(self, item):\n        if len(self.__items) >= self.__max:\n            print("列表已满！")\n        else:\n            self.__items.append(item)\n    def show(self): print(self.__items)\nll = LimitedList(3)\nfor i in range(5): ll.add(i)\nll.show()', check:function(o){return o.indexOf("已满")!==-1;}},
  {desc:"用私有方法实现内部逻辑封装", template:'# 私有方法\n', hint:'class Calculator:\n    def __validate(self, a, b):\n        if not isinstance(a, (int,float)) or not isinstance(b, (int,float)):\n            raise ValueError("必须是数字")\n    def add(self, a, b):\n        self.__validate(a, b)\n        return a + b\nc = Calculator()\nprint(c.add(3, 5))\ntry: c.add("a", 1)\nexcept ValueError as e: print(e)', check:function(o){return o.indexOf("8")!==-1;}},
  {desc:"实现一个不可变的Point类", template:'# 不可变对象\n', hint:'class Point:\n    def __init__(self, x, y):\n        self.__x = x\n        self.__y = y\n    @property\n    def x(self): return self.__x\n    @property\n    def y(self): return self.__y\n    def __str__(self): return f"({self.__x}, {self.__y})"\np = Point(3, 4)\nprint(p)\ntry: p.x = 10\nexcept AttributeError: print("Point是不可变的")', check:function(o){return o.indexOf("(3, 4)")!==-1;}},
  {desc:"综合：创建一个安全的银行账户类（余额私有，有验证）", template:'# 安全银行账户\n', hint:'class SafeAccount:\n    def __init__(self, owner, pin, balance=0):\n        self.__owner = owner\n        self.__pin = pin\n        self.__balance = balance\n    def deposit(self, pin, amount):\n        if pin != self.__pin: print("PIN错误"); return\n        if amount <= 0: print("金额必须为正"); return\n        self.__balance += amount\n        print(f"存入{amount}，余额:{self.__balance}")\n    def get_balance(self, pin):\n        if pin != self.__pin: print("PIN错误"); return\n        print(f"余额: {self.__balance}")\nacc = SafeAccount("小明", "1234", 100)\nacc.deposit("1234", 50)\nacc.deposit("wrong", 50)\nacc.get_balance("1234")', check:function(o){return o.indexOf("PIN错误")!==-1;}}
],
"12-4": [
  {desc:"用type/isinstance/hasattr检查对象信息", template:'# 对象检测\n', hint:'class Hero:\n    def __init__(self): self.hp = 100; self.name = "勇者"\nh = Hero()\nprint(type(h))\nprint(hasattr(h, "hp"))\nprint(getattr(h, "name"))', check:function(o){return o.indexOf("True")!==-1;}},
  {desc:"用dir()列出对象的所有属性和方法", template:'s = "hello"\n', hint:'s = "hello"\nmethods = [m for m in dir(s) if not m.startswith("_")]\nprint(methods[:10])', check:function(o){return o.indexOf("upper")!==-1 || o.indexOf("lower")!==-1;}},
  {desc:"用getattr动态调用方法", template:'# 动态调用\n', hint:'class Math:\n    def add(self, a, b): return a+b\n    def mul(self, a, b): return a*b\nm = Math()\nfor op in ["add", "mul"]:\n    func = getattr(m, op)\n    print(f"{op}(3,4) = {func(3,4)}")', check:function(o){return o.indexOf("7")!==-1 && o.indexOf("12")!==-1;}},
  {desc:"用setattr动态设置属性", template:'# 动态设置\n', hint:'class Config:\n    pass\nc = Config()\nfor key, val in {"host":"localhost","port":8080}.items():\n    setattr(c, key, val)\nprint(c.host)\nprint(c.port)', check:function(o){return o.indexOf("localhost")!==-1;}},
  {desc:"用isinstance判断对象属于哪个类", template:'# 类型判断\n', hint:'class Cat: pass\nclass Dog: pass\nclass Fish: pass\nanimals = [Cat(), Dog(), Fish(), Cat(), Dog()]\nfor a in animals:\n    if isinstance(a, Cat): print("猫")\n    elif isinstance(a, Dog): print("狗")\n    else: print("鱼")', check:function(o){return o.indexOf("猫")!==-1;}},
  {desc:"用hasattr检查对象是否有某方法再调用", template:'# 安全调用\n', hint:'class A:\n    def hello(self): print("Hello from A")\nclass B:\n    pass\nfor obj in [A(), B()]:\n    if hasattr(obj, "hello"):\n        obj.hello()\n    else:\n        print(f"{type(obj).__name__}没有hello方法")', check:function(o){return o.indexOf("Hello")!==-1;}},
  {desc:"用type()创建动态类", template:'# 动态类\n', hint:'MyClass = type("MyClass", (), {"x": 42, "greet": lambda self: print("Hi!")})\nobj = MyClass()\nprint(obj.x)\nobj.greet()', check:function(o){return o.indexOf("42")!==-1;}},
  {desc:"比较type和isinstance的区别", template:'# type vs isinstance\n', hint:'class Animal: pass\nclass Dog(Animal): pass\nd = Dog()\nprint(f"type: {type(d) == Dog}")\nprint(f"type: {type(d) == Animal}")\nprint(f"isinstance: {isinstance(d, Dog)}")\nprint(f"isinstance: {isinstance(d, Animal)}")', check:function(o){return o.indexOf("False")!==-1 && o.indexOf("True")!==-1;}},
  {desc:"实现一个简单的对象序列化（转为字典）", template:'# 对象转字典\n', hint:'class Person:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age\n    def to_dict(self):\n        return {k:v for k,v in self.__dict__.items()}\np = Person("小明", 10)\nprint(p.to_dict())', check:function(o){return o.indexOf("小明")!==-1;}},
  {desc:"用vars()获取对象的__dict__", template:'# vars()\n', hint:'class Student:\n    def __init__(self, name, score):\n        self.name = name\n        self.score = score\ns = Student("小红", 95)\nprint(vars(s))\nfor k, v in vars(s).items():\n    print(f"  {k}: {v}")', check:function(o){return o.indexOf("name")!==-1;}}
],
  });
})();
